# 1 Importownie bibliotek

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math

# 2 Importowanie pliku w PANDAS

## Jest kilka sposobów, najprostszy jest gdy mamy *.CSV:

df1=pd.read_csv('ks-projects-201801.csv')

df2=pd.read_csv('./course-files/ks-projects-201801.csv')

**Uwagi:**
    1. plik ks-projects-201801.csv w **DF2** ma podaną ściężkę jak widać spoza lokalizacji ROOTa ./jupitera, w zwkiązku z tym jest "./"
    2. można w jupiterze używać TABa po "./"
    3. w przypadku **DF1** gdy mamy notebook w tej samej lokalizacji co plik to nie musimy używać "./"
    
 **Pandas obsuguje inne pliki, takie jak np:**
    1. excel
    2. html
    3. jason
    4. schowek
 Wszystko jest pod tabulatorem po .read_

## Import poszczególnych kolumn na przykładzie *.CSV

df1=pd.read_csv('ks-projects-201801.csv',usecols=['usd pledged','usd_pledged_real'])

In [0]:
df1=pd.read_csv('ks-projects-201801.csv',usecols=['usd pledged','usd_pledged_real'])
#.head() wyświetla 5 krotek - jeśli będzie parametr (10) to będzie 10 krotek
print(df1.head())
print('\n')
#.tail() wyświetla 5 krotek - jeśli będzie parametr (10) to będzie 10 krotek
print(df1.tail())

   usd pledged  usd_pledged_real
0          0.0               0.0
1        100.0            2421.0
2        220.0             220.0
3          1.0               1.0
4       1283.0            1283.0


        usd pledged  usd_pledged_real
378656         25.0              25.0
378657        155.0             155.0
378658         20.0              20.0
378659        200.0             200.0
378660        524.0             524.0

In [0]:
df1=pd.read_csv('ks-projects-201801.csv',usecols=['usd pledged','usd_pledged_real'])
df1.head()

   usd pledged  usd_pledged_real
0          0.0               0.0
1        100.0            2421.0
2        220.0             220.0
3          1.0               1.0
4       1283.0            1283.0

## 2.1 Inne sposoby importu plików:
import csv

**konstrukcja *with* pozwala na otworzenie pliku i korzystanie z niego wewnątrz niej, po jej opuszczeniu automatycznie zamknie strumień odczytu**

with open('plik.csv', 'r') as csvfile:

**deklarujemy nasz *czytacz* parametr *delimiter* jest opcjonalny i wskazuje jaki został w pliku użyty separator**

csvreader = csv.reader(csvfile, delimiter=',')

**pojawia się nowy paramet encoding ustawiony na utf-8**

with open('plik.csv', 'r', encoding='utf-8') as csvfile:
    csvreader = csv.reader(csvfile, delimiter=',')

In [0]:
#czytanie z pliku z podziałem na linie (rt - czytaj jako tekst) NALEŻY ZROBIĆ PTK 2.5 !!!
with open("file.csv", "rt") as f:
  lines = f.readlines()

#lista zawierająca po jednej pozycji na linię z pliku (tekst zawiera znak nowej lini)
lines

['col 1, col 2, col 3\n', 'line 1, 1, 2\n', 'line 2, 2, 3 \n']

## 2.2 Indeksowanie Serii/DataFrame

1. Gdy zaimportujemy domyślnie nasz plik, indeksem staje się domyślnie utworzona kolumna. Widać to poniżej:

In [0]:
df1=pd.read_csv('ks-projects-201801.csv')
df1.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00

2. Można to zmienić gdy przypiszemy indeks parametrem **index_col**, podczas importu pliku. Poniżej przykład z df2

In [0]:
df2=pd.read_csv('ks-projects-201801.csv', index_col='ID')
df2.head()

,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
ID,,,,,,,,,,,,,,
1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00

## 2.3 Filtrowanie Serii/DataFrame
1. Przypisujemy kolumnę do zmiennej np o nazwie zmiennej kolumny **usd_pledged_real**, z już zaimportowanego pliku do zmiennej **df1**

In [0]:
usd_pledged_real=df1['usd_pledged_real']
print(usd_pledged_real.head())

0       0.0
1    2421.0
2     220.0
3       1.0
4    1283.0
Name: usd_pledged_real, dtype: float64

2. Zgodnie z good pactices nazywamy w nazwie zmiennej słowa filtr i przypisujmey do niej już samą kolumnę, następnie **==** wpisujemy wartość jaka nas interesuje

In [0]:
df1Filter100 = usd_pledged_real == 100
print(df1Filter100.head())

0    False
1    False
2    False
3    False
4    False
Name: usd_pledged_real, dtype: bool

3. wynik zwraca zawsze wartości boolowe
4. No i wreszcie chcemy wyświetlić wszystkie wartości z df1, które w kolumnie **usd_pledged_real** mają wartość **100**, dodatkowo usuwamy puste krotki poprzez dodanie **.dropna**

In [0]:
print(df1.where(df1Filter100).dropna().head(10))

                ID                                               name  \
278   1.001243e+09                                  The FUSIONproject
333   1.001514e+09  Help start Jacksonville's FIRST Paint Your Own...
395   1.001843e+09        Gospel Jazz Independant Artist - CD Project
699   1.003441e+09  Vanilley Bean Treats! For life's "sweet" moments!
831   1.004071e+09                      1 Man, 10 Days, 100+ Canvases
909   1.004514e+09                         Give in to Sweet Surrender
1112  1.005617e+09                            The Dousing Sauce Story
1297  1.006646e+09                The Die: A Comedy Horror Short Film
1516  1.007753e+09                                    Blue Haus Grill
1530  1.007821e+09                             The Life Story Project

         category main_category currency    deadline     goal  \
278   Documentary  Film & Video      USD  2011-04-24   5000.0
333      Ceramics           Art      USD  2014-11-04   8000.0
395         Music         Music      USD  2011-06-18   7000.0
699          Food          Food      USD  2012-12-25   1500.0
831      Painting           Art      USD  2012-11-09  10000.0
909   Small Batch          Food      USD  2015-02-18   5000.0
1112         Food          Food      USD  2015-06-01  25000.0
1297       Shorts  Film & Video      USD  2011-10-07   1000.0
1516         Food          Food      USD  2014-04-10   3000.0
1530        Print    Journalism      USD  2014-11-03   2500.0

                 launched  pledged   state  backers country  usd pledged  \
278   2011-03-24 00:08:46    100.0  failed      1.0      US        100.0
333   2014-09-25 00:57:10    100.0  failed      1.0      US        100.0
395   2011-05-19 21:34:49    100.0  failed      1.0      US        100.0
699   2012-11-20 01:41:51    100.0  failed      3.0      US        100.0
831   2012-10-05 10:13:37    100.0  failed      1.0      US        100.0
909   2015-01-19 02:28:05    100.0  failed      1.0      US        100.0
1112  2015-04-08 07:55:56    100.0  failed      3.0      US        100.0
1297  2011-09-07 02:07:41    100.0  failed      2.0      US        100.0
1516  2014-03-11 20:07:47    100.0  failed      1.0      US        100.0
1530  2014-10-04 03:14:42    100.0  failed      1.0      US        100.0

      usd_pledged_real  usd_goal_real
278              100.0         5000.0
333              100.0         8000.0
395              100.0         7000.0
699              100.0         1500.0
831              100.0        10000.0
909              100.0         5000.0
1112             100.0        25000.0
1297             100.0         1000.0
1516             100.0         3000.0
1530             100.0         2500.0

5. Można oczywiście łączyć kilka filtrów za pomocą operatora **&**

**UWAGA** Najprawdopodobniej jest to filtrowanie warunkowe, a w przypadku łączenia filtrów oba warunki muszą być spełnione

In [0]:
df1FilterMore100 = usd_pledged_real >= 100

print(df1.where(df1Filter100 & df1FilterMore100).dropna())

                  ID                                               name  \
278     1.001243e+09                                  The FUSIONproject
333     1.001514e+09  Help start Jacksonville's FIRST Paint Your Own...
395     1.001843e+09        Gospel Jazz Independant Artist - CD Project
699     1.003441e+09  Vanilley Bean Treats! For life's "sweet" moments!
831     1.004071e+09                      1 Man, 10 Days, 100+ Canvases
909     1.004514e+09                         Give in to Sweet Surrender
1112    1.005617e+09                            The Dousing Sauce Story
1297    1.006646e+09                The Die: A Comedy Horror Short Film
1516    1.007753e+09                                    Blue Haus Grill
1530    1.007821e+09                             The Life Story Project
1597    1.008199e+09             Preparing you for today and our future
1807    1.009252e+09  EKRt : Explanation Kills RRt A Tshirt Line © (...
2141    1.011197e+09   House of Royalty alcohol on demand delivery app.
2163    1.011319e+09                                   Murder: A Comedy
2280    1.011833e+09                              Hesting Power Turbine
2396    1.012421e+09                             Rhallen Campaign World
3053    1.015781e+09            Caleb Mikesell - Music Video: "Be Okay"
3063    1.015804e+09  Fusion Confusion --Mix of the most DELICOUS RE...
3280    1.016933e+09         Manufacture of Bijouz Full Figured Fashion
3286    1.016968e+09  Diva of Spiritual Voice/Hidden jewel from !NEW...
3304    1.017069e+09            Wastebasket Whatnots: Jewelry and Gifts
3351    1.017306e+09  Hot Pants and Helmets: A Modern Roller Derby S...
3523    1.018121e+09              "25 years of the Mafia Game" Workshop
3619    1.018706e+08                            Vista-Ville Skateboards
3858    1.019836e+09  The Peace Wall: A 2012 Interactive Burning Man...
3983    1.020521e+09                                            Breathe
3990    1.020538e+09                     Help Larry represent his music
4285    1.022028e+09  BrokenRail Debut Album w/ Shinedown/Crossfade ...
4470    1.022855e+09                                Honor Among Thieves
4626    1.023634e+09                  G.P.W.F.L.Y. So Fly - Music Video
...              ...                                                ...
373684  9.741588e+08                                    Raw Truth Radio
373700  9.742751e+08  Think torture is wrong?  Join us in drafting a...
373728  9.744199e+08                            Pepesaur! I choose you!
374175  9.768246e+08                                   Toppersunglasses
374444  9.781704e+08                               Life Alarm Phone App
374458  9.782798e+08                      EXCELSIOR SCHOOL OF FINE ARTS
374579  9.789342e+08          Fresh Tanks -  Tops Inspired by customers
374771  9.800037e+08                   Drew Low: Operation Opera Singer
374802  9.801138e+08                        Tolento's Grille (Canceled)
375240  9.823636e+08  Alice Practice's First Album: The Girls Withou...
375388  9.830402e+08                       THEIR PREFERENCES (Canceled)
375597  9.842704e+08                                            Liberte
376085  9.868470e+08                        LiveMix Video Presentations
376106  9.869360e+06                            Angel Light Celebration
376121  9.870478e+08  SEX-DRUGS-THUGS - UNTOLD TRUTH BEHIND NY JAIL ...
376127  9.870725e+08  MashaO Design in 1st Independent Show @Bellevu...
376129  9.870782e+08                                        Rift Jumper
376465  9.887421e+08  Photo Memory Blocks - Favorite photo transferr...
376619  9.896142e+07  A QUIET PLACE IN THE WOODS gay horror film in ...
377037  9.917731e+08                                     Fighting Blind
377261  9.929372e+08                Gay Veteran Artist in Port Townsend
377334  9.933833e+08  50 Recipes I Can Cook With My Daughter/Son. A ...
377482  9.941391e+08                                      MUTE New York
377510  9.942919e+08                              Claudia's Craft Boxes
377624  9.948498e+08  A Short Film on the Election in Turkey (Canceled)
377900  9.962912e+08                                     The Year After
378043  9.970334e+07                 Inner Cities in America (Canceled)
378093  9.973334e+08                             Jai Allen's EP Project
378461  9.989923e+08                                     The Watchmaker
378640  9.998936e+08                          Ciridian Helix (Canceled)

                category main_category currency    deadline     goal  \
278          Documentary  Film & Video      USD  2011-04-24   5000.0
333             Ceramics           Art      USD  2014-11-04   8000.0
395                Music         Music      USD  2011-06-18   7000.0
699                 Food          Food      USD  2012-12-25   1500.0
831             Painting           Art      USD  2012-11-09  10000.0
909          Small Batch          Food      USD  2015-02-18   5000.0
1112                Food          Food      USD  2015-06-01  25000.0
1297              Shorts  Film & Video      USD  2011-10-07   1000.0
1516                Food          Food      USD  2014-04-10   3000.0
1530               Print    Journalism      USD  2014-11-03   2500.0
1597          Nonfiction    Publishing      USD  2017-09-23  15000.0
1807             Apparel       Fashion      USD  2015-12-21   5000.0
2141                Apps    Technology      USD  2017-04-15  12000.0
2163      Narrative Film  Film & Video      USD  2011-06-02   3500.0
2280            Hardware    Technology      USD  2014-09-29   5000.0
2396      Tabletop Games         Games      USD  2016-11-04   1000.0
3053               Music         Music      USD  2012-10-24    100.0
3063                Food          Food      USD  2013-01-04  25000.0
3280             Fashion       Fashion      USD  2012-11-08   2000.0
3286         World Music         Music      USD  2012-07-18  80000.0
3304              Crafts        Crafts      USD  2011-10-24   5000.0
3351         Photography   Photography      USD  2012-05-31    500.0
3523               Games         Games      USD  2012-10-29  10000.0
3619      Product Design        Design      USD  2014-05-12    500.0
3858      Conceptual Art           Art      USD  2012-08-03   2500.0
3983         Documentary  Film & Video      USD  2017-05-21  30000.0
3990               Music         Music      USD  2016-07-02   1000.0
4285               Music         Music      USD  2010-05-27  22000.0
4470              Shorts  Film & Video      USD  2013-02-02   5000.0
4626        Film & Video  Film & Video      USD  2011-08-23   3500.0
...                  ...           ...      ...         ...      ...
373684             Music         Music      USD  2013-10-27  27000.0
373700      Film & Video  Film & Video      USD  2010-05-08  10000.0
373728       Mixed Media           Art      USD  2017-02-05    275.0
374175       Accessories       Fashion      USD  2016-07-03  15000.0
374444        Technology    Technology      USD  2015-09-06  18000.0
374458           Musical       Theater      USD  2016-08-11  30000.0
374579           Fashion       Fashion      USD  2014-02-16  25000.0
374771   Classical Music         Music      USD  2012-05-29   4000.0
374802       Restaurants          Food      USD  2014-12-08  45000.0
375240              Rock         Music      USD  2011-12-01  10000.0
375388       Documentary  Film & Video      USD  2012-10-10   5000.0
375597         Thrillers  Film & Video      USD  2016-12-11   5400.0
376085          Software    Technology      USD  2015-12-17   5000.0
376106  Children's Books    Publishing      USD  2012-01-08   5000.0
376121        Nonfiction    Publishing      USD  2015-08-19   5000.0
376127           Fashion       Fashion      USD  2012-08-01   8000.0
376129    Tabletop Games         Games      USD  2018-01-03  10000.0
376465       Woodworking        Crafts      USD  2015-09-19   2000.0
376619    Narrative Film  Film & Video      USD  2012-02-01   5000.0
377037       Documentary  Film & Video      USD  2017-03-12  15000.0
377261       Mixed Media           Art      USD  2016-03-04   5000.0
377334        Nonfiction    Publishing      USD  2012-10-03  12500.0
377482           Apparel       Fashion      USD  2015-10-07   2500.0
377510               DIY        Crafts      USD  2015-10-23  10000.0
377624            Shorts  Film & Video      USD  2011-06-19    500.0
377900       Documentary  Film & Video      USD  2015-09-16   3500.0
378043       Documentary  Film & Video      USD  2015-12-11    750.0
378093             Faith         Music      USD  2017-11-09   3500.0
378461        Indie Rock         Music      USD  2011-05-20  11000.0
378640           Fiction    Publishing      USD  2014-09-11   1000.0

                   launched  pledged       state  backers country  \
278     2011-03-24 00:08:46    100.0      failed      1.0      US
333     2014-09-25 00:57:10    100.0      failed      1.0      US
395     2011-05-19 21:34:49    100.0      failed      1.0      US
699     2012-11-20 01:41:51    100.0      failed      3.0      US
831     2012-10-05 10:13:37    100.0      failed      1.0      US
909     2015-01-19 02:28:05    100.0      failed      1.0      US
1112    2015-04-08 07:55:56    100.0      failed      3.0      US
1297    2011-09-07 02:07:41    100.0      failed      2.0      US
1516    2014-03-11 20:07:47    100.0      failed      1.0      US
1530    2014-10-04 03:14:42    100.0      failed      1.0      US
1597    2017-08-24 20:02:08    100.0      failed      1.0      US
1807    2015-11-21 02:33:06    100.0    canceled      1.0      US
2141    2017-03-01 17:10:49    100.0      failed      3.0      US
2163    2011-03-11 09:58:34    100.0      failed      3.0      US
2280    2014-08-01 00:41:26    100.0      failed      1.0      US
2396    2016-09-20 20:29:08    100.0      failed      4.0      US
3053    2012-10-04 20:29:23    100.0  successful      1.0      US
3063    2012-12-05 08:54:17    100.0      failed      1.0      US
3280    2012-09-24 09:42:13    100.0      failed      7.0      US
3286    2012-06-18 21:58:50    100.0      failed      2.0      US
3304    2011-09-24 06:11:14    100.0      failed      2.0      US
3351    2012-05-03 01:54:18    100.0      failed      6.0      US
3523    2012-09-28 20:38:13    100.0      failed      4.0      US
3619    2014-04-12 00:03:15    100.0      failed      1.0      US
3858    2012-07-20 19:00:37    100.0      failed      1.0      US
3983    2017-04-29 00:55:29    100.0      failed      1.0      US
3990    2016-06-02 19:50:49    100.0      failed      1.0      US
4285    2010-04-24 08:33:59    100.0      failed      1.0      US
4470    2012-12-04 02:33:58    100.0      failed      2.0      US
4626    2011-07-13 21:42:48    100.0      failed      2.0      US
...                     ...      ...         ...      ...     ...
373684  2013-09-27 15:23:42    100.0      failed      1.0      US
373700  2010-04-05 23:18:18    100.0    canceled      1.0      US
373728  2017-01-06 06:46:44    100.0      failed     10.0      US
374175  2016-05-04 21:46:01    100.0      failed      2.0      US
374444  2015-07-23 00:52:26    100.0      failed      1.0      US
374458  2016-06-12 01:16:52    100.0      failed      1.0      US
374579  2013-12-18 19:14:50    100.0      failed      4.0      US
374771  2012-05-15 17:18:00    100.0      failed      3.0      US
374802  2014-10-24 00:50:26    100.0    canceled      1.0      US
375240  2011-10-27 19:58:19    100.0    canceled      1.0      US
375388  2012-09-10 05:12:54    100.0    canceled      4.0      US
375597  2016-11-27 16:04:12    100.0      failed      1.0      US
376085  2015-11-02 18:24:29    100.0      failed      2.0      US
376106  2011-12-09 23:33:03    100.0      failed      1.0      US
376121  2015-07-05 03:26:14    100.0      failed      6.0      US
376127  2012-07-20 20:09:42    100.0      failed      2.0      US
376129  2017-12-04 05:33:06    100.0    canceled      5.0      US
376465  2015-08-20 23:06:35    100.0      failed      5.0      US
376619  2011-12-27 22:29:25    100.0      failed      2.0      US
377037  2017-02-10 17:19:56    100.0      failed      1.0      US
377261  2016-01-04 17:53:38    100.0      failed      1.0      US
377334  2012-08-04 03:33:24    100.0      failed      3.0      US
377482  2015-08-08 06:22:15    100.0      failed      1.0      US
377510  2015-09-23 21:25:16    100.0      failed      1.0      US
377624  2011-05-20 03:16:03    100.0    canceled      2.0      US
377900  2015-08-17 08:16:19    100.0      failed      1.0      US
378043  2015-11-11 20:14:20    100.0    canceled      6.0      US
378093  2017-10-10 10:45:41    100.0      failed      2.0      US
378461  2011-04-06 01:44:46    100.0      failed      1.0      US
378640  2014-08-08 21:49:31    100.0    canceled      2.0      US

        usd pledged  usd_pledged_real  usd_goal_real
278           100.0             100.0         5000.0
333           100.0             100.0         8000.0
395           100.0             100.0         7000.0
699           100.0             100.0         1500.0
831           100.0             100.0        10000.0
909           100.0             100.0         5000.0
1112          100.0             100.0        25000.0
1297          100.0             100.0         1000.0
1516          100.0             100.0         3000.0
1530          100.0             100.0         2500.0
1597            0.0             100.0        15000.0
1807          100.0             100.0         5000.0
2141           75.0             100.0        12000.0
2163          100.0             100.0         3500.0
2280          100.0             100.0         5000.0
2396           70.0             100.0         1000.0
3053          100.0             100.0          100.0
3063          100.0             100.0        25000.0
3280          100.0             100.0         2000.0
3286          100.0             100.0        80000.0
3304          100.0             100.0         5000.0
3351          100.0             100.0          500.0
3523          100.0             100.0        10000.0
3619          100.0             100.0          500.0
3858          100.0             100.0         2500.0
3983            0.0             100.0        30000.0
3990          100.0             100.0         1000.0
4285          100.0             100.0        22000.0
4470          100.0             100.0         5000.0
4626          100.0             100.0         3500.0
...             ...               ...            ...
373684        100.0             100.0        27000.0
373700        100.0             100.0        10000.0
373728         20.0             100.0          275.0
374175        100.0             100.0        15000.0
374444        100.0             100.0        18000.0
374458          0.0             100.0        30000.0
374579        100.0             100.0        25000.0
374771        100.0             100.0         4000.0
374802        100.0             100.0        45000.0
375240        100.0             100.0        10000.0
375388        100.0             100.0         5000.0
375597          0.0             100.0         5400.0
376085        100.0             100.0         5000.0
376106        100.0             100.0         5000.0
376121        100.0             100.0         5000.0
376127        100.0             100.0         8000.0
376129         20.0             100.0        10000.0
376465        100.0             100.0         2000.0
376619        100.0             100.0         5000.0
377037          0.0             100.0        15000.0
377261        100.0             100.0         5000.0
377334        100.0             100.0        12500.0
377482        100.0             100.0         2500.0
377510        100.0             100.0        10000.0
377624        100.0             100.0          500.0
377900        100.0             100.0         3500.0
378043        100.0             100.0          750.0
378093          0.0             100.0         3500.0
378461        100.0             100.0        11000.0
378640        100.0             100.0         1000.0

[2436 rows x 15 columns]

## 2.4 Czyszczenie danych

1. Można poczyścić dane z warości NULL, dzięki metodzie **.dropna**, parametr **inplace=True** informuje o zapisaniu zmian do df1!

In [0]:
df1.dropna(inplace=True)

## 2.5 Zapisywanie plików

In [0]:
#pisanie do pliku (wt - zapisz jako tekst)
with open("file.csv", "wt") as f:
  f.write("col 1, col 2, col 3\n")
  f.write("line 1, 1, 2\n")
  f.write("line 2, 2, 3 \n")

## 2.6 Tworzenie ramki danych

In [0]:
#tworzenie ramki danych z listy rekorodow: pierwszy argument - lista rekordów, columns - nazwy kolumn
df = pd.DataFrame.from_records([("a",1),("b",2)], columns = ["col 1", "col 2"])
df

## 2.7 Pobieranie wartości z ramki danych, podstawowe poruszanie się i operacje

In [0]:
from sklearn.datasets import load_boston
import pandas as pd
#pobieramy ścieżkę do pliku w którym znajduje się zbiór danych, zbiór danych jest dostępny w postaci pliku CSV
boston_dataset_path = load_boston()['filename'] 
print(boston_dataset_path)

#czytamy zbiór danych z pliku
df = pd.read_csv(boston_dataset_path, header = 1) #header = 1 oznacza, że w pierwszej linijce pliku znajdują się nazwy kolumn
print(df)

/usr/local/lib/python3.6/dist-packages/sklearn/datasets/data/boston_house_prices.csv
        CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0    0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1    0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2    0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3    0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4    0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
..       ...   ...    ...   ...    ...  ...  ...      ...     ...    ...   ...
501  0.06263   0.0  11.93     0  0.573  ...  273     21.0  391.99   9.67  22.4
502  0.04527   0.0  11.93     0  0.573  ...  273     21.0  396.90   9.08  20.6
503  0.06076   0.0  11.93     0  0.573  ...  273     21.0  396.90   5.64  23.9
504  0.10959   0.0  11.93     0  0.573  ...  273     21.0  393.45   6.48  22.0
505  0.04741   0.0  11.93     0  0.573  ...  273     21.0  396.90   7.88  11.9

[506 rows x 14 columns]

In [0]:
#dostęp do elementów z kolumny:
#wybrana kolumna
print("*"*20)
print(df["CRIM"])

#wybrana komórka .iat[numer wiersza, numer kolumny]
print("*"*20)
print("wartość wiersz 10, kolumny 0",df.iat[10,0])

#kilka wierszy z danej kolumny .iloc[selektor wierszy, numer kolumny]
print("*"*20)
print(df.iloc[0:10,0])

#kilka wierszy z danej kolumny na podstawie nazyw kolumny 
#df.columns.get_loc("CRIM") zwraca numer kolumny o danej nazwie
print("*"*20)
print(df.iloc[0:10,df.columns.get_loc("CRIM")])

********************
0      0.00632
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...
501    0.06263
502    0.04527
503    0.06076
504    0.10959
505    0.04741
Name: CRIM, Length: 506, dtype: float64
********************
wartość wiersz 10, kolumny 0 0.22489
********************
0    0.00632
1    0.02731
2    0.02729
3    0.03237
4    0.06905
5    0.02985
6    0.08829
7    0.14455
8    0.21124
9    0.17004
Name: CRIM, dtype: float64
********************
0    0.00632
1    0.02731
2    0.02729
3    0.03237
4    0.06905
5    0.02985
6    0.08829
7    0.14455
8    0.21124
9    0.17004
Name: CRIM, dtype: float64

In [0]:
#Nawigacja po ramce danych

#lista kolumn
print("kolumny", list(df.columns))

#liczba kolumn 
print("#kolumn:", df.shape[1], "#wierszy:", df.shape[0])

kolumny ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
#kolumn: 14 #wierszy: 506

In [0]:
#statystyki
print(df["CRIM"].unique()[0:10])
print(df["CRIM"].mean())
print(df["CRIM"].max())
print(df["CRIM"].min())
print(df["CRIM"].std())
print(df["CRIM"].median())

[0.00632 0.02731 0.02729 0.03237 0.06905 0.02985 0.08829 0.14455 0.21124
 0.17004]
3.6135235573122535
88.9762
0.00632
8.601545105332487
0.25651

In [0]:
#wyświetl wiersze dla których crime per capita (CRIM) > 20 
#w df.loc[warunek_filtrowania]
df.loc[df.CRIM > 20]

        CRIM   ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
378  23.6482  0.0   18.1     0  0.671  ...  666     20.2  396.90  23.69  13.1
380  88.9762  0.0   18.1     0  0.671  ...  666     20.2  396.90  17.21  10.4
384  20.0849  0.0   18.1     0  0.700  ...  666     20.2  285.83  30.63   8.8
386  24.3938  0.0   18.1     0  0.700  ...  666     20.2  396.90  28.28  10.5
387  22.5971  0.0   18.1     0  0.700  ...  666     20.2  396.90  31.99   7.4
398  38.3518  0.0   18.1     0  0.693  ...  666     20.2  396.90  30.59   5.0
400  25.0461  0.0   18.1     0  0.693  ...  666     20.2  396.90  26.77   5.6
403  24.8017  0.0   18.1     0  0.693  ...  666     20.2  396.90  19.77   8.3
404  41.5292  0.0   18.1     0  0.693  ...  666     20.2  329.46  27.38   8.5
405  67.9208  0.0   18.1     0  0.693  ...  666     20.2  384.97  22.98   5.0
406  20.7162  0.0   18.1     0  0.659  ...  666     20.2  370.22  23.34  11.9
410  51.1358  0.0   18.1     0  0.597  ...  666     20.2    2.60  10.11  15.0
413  28.6558  0.0   18.1     0  0.597  ...  666     20.2  210.97  20.08  16.3
414  45.7461  0.0   18.1     0  0.693  ...  666     20.2   88.27  36.98   7.0
417  25.9406  0.0   18.1     0  0.679  ...  666     20.2  127.36  26.64  10.4
418  73.5341  0.0   18.1     0  0.679  ...  666     20.2   16.45  20.62   8.8
427  37.6619  0.0   18.1     0  0.679  ...  666     20.2   18.82  14.52  10.9
440  22.0511  0.0   18.1     0  0.740  ...  666     20.2  391.45  22.11  10.5

[18 rows x 14 columns]

In [0]:
#w df.loc[warunek_filtrowania, kolumna]
df.loc[df.CRIM > 20, "CRIM"]

378    23.6482
380    88.9762
384    20.0849
386    24.3938
387    22.5971
398    38.3518
400    25.0461
403    24.8017
404    41.5292
405    67.9208
406    20.7162
410    51.1358
413    28.6558
414    45.7461
417    25.9406
418    73.5341
427    37.6619
440    22.0511
Name: CRIM, dtype: float64

In [0]:
#wyświetl oferty znajdujące się w lokalizacjach z małą przestępczością crime per capita (CRIM) < 0.1
#oraz niską proporcją uczeń per nauczyciel (PTRATIO) < 20
#df.loc[warunek_1 & warunek_2]; trzeba pamiętać, żeby każdy warunek umieścić w ()
df.loc[(df.CRIM < 0.1) & (df.PTRATIO < 20)]

        CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0    0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1    0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2    0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3    0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4    0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
..       ...   ...    ...   ...    ...  ...  ...      ...     ...    ...   ...
349  0.02899  40.0   1.25     0  0.429  ...  335     19.7  389.85   5.89  26.6
350  0.06211  40.0   1.25     0  0.429  ...  335     19.7  396.90   5.98  22.9
351  0.07950  60.0   1.69     0  0.411  ...  411     18.3  370.78   5.49  24.1
352  0.07244  60.0   1.69     0  0.411  ...  411     18.3  392.33   7.79  18.6
353  0.01709  90.0   2.02     0  0.410  ...  187     17.0  384.46   4.50  30.1

[138 rows x 14 columns]

In [0]:
#tworzenie kopi ramki danych na podstawie warunku filtrowania (analogicznie do kopiowania list)
df2 = df.loc[(df.CRIM < 0.1) & (df.PTRATIO < 20)].copy()
df2

        CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0    0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1    0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2    0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3    0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4    0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
..       ...   ...    ...   ...    ...  ...  ...      ...     ...    ...   ...
349  0.02899  40.0   1.25     0  0.429  ...  335     19.7  389.85   5.89  26.6
350  0.06211  40.0   1.25     0  0.429  ...  335     19.7  396.90   5.98  22.9
351  0.07950  60.0   1.69     0  0.411  ...  411     18.3  370.78   5.49  24.1
352  0.07244  60.0   1.69     0  0.411  ...  411     18.3  392.33   7.79  18.6
353  0.01709  90.0   2.02     0  0.410  ...  187     17.0  384.46   4.50  30.1

[138 rows x 14 columns]

In [0]:
#modyfikowanie wartości

df.iloc[0:3,0] = 1
df

        CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0    1.00000  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1    1.00000   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2    1.00000   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3    0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4    0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
..       ...   ...    ...   ...    ...  ...  ...      ...     ...    ...   ...
501  0.06263   0.0  11.93     0  0.573  ...  273     21.0  391.99   9.67  22.4
502  0.04527   0.0  11.93     0  0.573  ...  273     21.0  396.90   9.08  20.6
503  0.06076   0.0  11.93     0  0.573  ...  273     21.0  396.90   5.64  23.9
504  0.10959   0.0  11.93     0  0.573  ...  273     21.0  393.45   6.48  22.0
505  0.04741   0.0  11.93     0  0.573  ...  273     21.0  396.90   7.88  11.9

[506 rows x 14 columns]

In [0]:
#modyfikowanie wartości

df.loc[df.CRIM == 1, "CRIM"] = 2
df

        CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0    2.00000  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1    2.00000   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2    2.00000   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3    0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4    0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
..       ...   ...    ...   ...    ...  ...  ...      ...     ...    ...   ...
501  0.06263   0.0  11.93     0  0.573  ...  273     21.0  391.99   9.67  22.4
502  0.04527   0.0  11.93     0  0.573  ...  273     21.0  396.90   9.08  20.6
503  0.06076   0.0  11.93     0  0.573  ...  273     21.0  396.90   5.64  23.9
504  0.10959   0.0  11.93     0  0.573  ...  273     21.0  393.45   6.48  22.0
505  0.04741   0.0  11.93     0  0.573  ...  273     21.0  396.90   7.88  11.9

[506 rows x 14 columns]

In [0]:
#jeszcze raz ładujemy ramkę danych żeby nie było zmian z poprzednich fragmentów notebooka
from sklearn.datasets import load_boston
import pandas as pd
#pobieramy ścieżkę do pliku w którym znajduje się zbiór danych, zbiór danych jest dostępny w postaci pliku CSV
boston_dataset_path = load_boston()['filename'] 
print(boston_dataset_path)

#czytamy zbiór danych z pliku
df = pd.read_csv(boston_dataset_path, header = 1) #header = 1 oznacza, że w pierwszej linijce pliku znajdują się nazwy kolumn

#domyślnie filtrowanie po ramce danych tworzy widok, modyfikacja widoku powoduje modyfikację orginalnej ramki danych
df1 = df.iloc[0:10]
#jeśli chcemy wybrać fragment ramki na której chcemy pracować i nie modyfikować orginalnej ramki danych, musimy zrobić kopię
df2 = df.iloc[0:10].copy()
print("df")
print(df.head())
print("df1")
print(df1.head())
print("df2")
print(df2.head())

df.iloc[0:1,0] = 10
print("*"*10)
print("df")
print(df.head())
print("df1")
print(df1.head())
print("df2")
print(df2.head())

/usr/local/lib/python3.6/dist-packages/sklearn/datasets/data/boston_house_prices.csv
df
      CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]
df1
      CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]
df2
      CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]
**********
df
       CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0  10.00000  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1   0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2   0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3   0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4   0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]
df1
       CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0  10.00000  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1   0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2   0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3   0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4   0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]
df2
      CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [0]:
#jeszcze raz ładujemy ramkę danych żeby nie było zmian z poprzednich fragmentów notebooka
from sklearn.datasets import load_boston
import pandas as pd
#pobieramy ścieżkę do pliku w którym znajduje się zbiór danych, zbiór danych jest dostępny w postaci pliku CSV
boston_dataset_path = load_boston()['filename'] 
print(boston_dataset_path)

#czytamy zbiór danych z pliku
df = pd.read_csv(boston_dataset_path, header = 1) #header = 1 oznacza, że w pierwszej linijce pliku znajdują się nazwy kolumn
print("orginalna ramka danych")
print(df.head())
df.iat[0,0] = None
print("ramka danych z wartością NA w wierszu 0, kolumna CRIM")
print(df.head())
#usuń wiersze z wartościami brakującymi (tworzy kopię ramki danych)
df_no_na = df.dropna(how='any')
print("ramka danych po usunięciu wierszy z wartością")
print(df_no_na.head())

/usr/local/lib/python3.6/dist-packages/sklearn/datasets/data/boston_house_prices.csv
orginalna ramka danych
      CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]
ramka danych z wartością NA w wierszu 0, kolumna CRIM
      CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0      NaN  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]
ramka danych po usunięciu wierszy z wartością
      CRIM   ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
1  0.02731  0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729  0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237  0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905  0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
5  0.02985  0.0   2.18     0  0.458  ...  222     18.7  394.12   5.21  28.7

[5 rows x 14 columns]

In [0]:
#jeszcze raz ładujemy ramkę danych żeby nie było zmian z poprzednich fragmentów notebooka
from sklearn.datasets import load_boston
import pandas as pd
#pobieramy ścieżkę do pliku w którym znajduje się zbiór danych, zbiór danych jest dostępny w postaci pliku CSV
boston_dataset_path = load_boston()['filename'] 
print(boston_dataset_path)

#czytamy zbiór danych z pliku
df = pd.read_csv(boston_dataset_path, header = 1) #header = 1 oznacza, że w pierwszej linijce pliku znajdują się nazwy kolumn

print(df.head())
#usuwanie wierszy - dostajemy kopię ramki danych bez danego wiersza
df2 = df.drop(df.index[2])
print("orginalna ramka danych po usunięciu wiersza 2 pozostaje nie zmieniona")
print(df.head())
print("ramka danych po usunięciu wiersza 2")
print(df2.head())
#operacja inplace - usuwa wiersz w ramce danych
df.drop(df.index[2], inplace = True)
print("ramka danych po usunięciu wiersza 2 - inplace")
print(df.head())
#analogicznie możemy też używać filtrów (usuń wiersze dla których CRIM >= 0)
df3 = df.loc[df.CRIM < 1].copy()

#dodawanie nowych wierszy (append tworzy kopię ramki z nowymi wierszami)
print("koniec ramki danych")
print(df.tail())

for i in range(3):
  df = df.append({'CRIM': i, 'ZN': i}, ignore_index=True)

print("koniec ramki danych po dodaniu 3 wierszy")
print(df.tail())

/usr/local/lib/python3.6/dist-packages/sklearn/datasets/data/boston_house_prices.csv
      CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]
orginalna ramka danych po usunięciu wiersza 2 pozostaje nie zmieniona
      CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]
ramka danych po usunięciu wiersza 2
      CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
5  0.02985   0.0   2.18     0  0.458  ...  222     18.7  394.12   5.21  28.7

[5 rows x 14 columns]
ramka danych po usunięciu wiersza 2 - inplace
      CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
5  0.02985   0.0   2.18     0  0.458  ...  222     18.7  394.12   5.21  28.7

[5 rows x 14 columns]
koniec ramki danych
        CRIM   ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
501  0.06263  0.0  11.93     0  0.573  ...  273     21.0  391.99   9.67  22.4
502  0.04527  0.0  11.93     0  0.573  ...  273     21.0  396.90   9.08  20.6
503  0.06076  0.0  11.93     0  0.573  ...  273     21.0  396.90   5.64  23.9
504  0.10959  0.0  11.93     0  0.573  ...  273     21.0  393.45   6.48  22.0
505  0.04741  0.0  11.93     0  0.573  ...  273     21.0  396.90   7.88  11.9

[5 rows x 14 columns]
koniec ramki danych po dodaniu 3 wierszy
        CRIM   ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  MEDV
503  0.10959  0.0  11.93   0.0  0.573  ...  273.0     21.0  393.45   6.48  22.0
504  0.04741  0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   7.88  11.9
505  0.00000  0.0    NaN   NaN    NaN  ...    NaN      NaN     NaN    NaN   NaN
506  1.00000  1.0    NaN   NaN    NaN  ...    NaN      NaN     NaN    NaN   NaN
507  2.00000  2.0    NaN   NaN    NaN  ...    NaN      NaN     NaN    NaN   NaN

[5 rows x 14 columns]

## 2.8 łączenie ramek danych

In [0]:
#jeszcze raz ładujemy ramkę danych żeby nie było zmian z poprzednich fragmentów notebooka
from sklearn.datasets import load_boston
import pandas as pd
#pobieramy ścieżkę do pliku w którym znajduje się zbiór danych, zbiór danych jest dostępny w postaci pliku CSV
boston_dataset_path = load_boston()['filename'] 
print(boston_dataset_path)

#czytamy zbiór danych z pliku
df = pd.read_csv(boston_dataset_path, header = 1) #header = 1 oznacza, że w pierwszej linijce pliku znajdują się nazwy kolumn

df1 = df.iloc[0:3]
df2 = df.iloc[3:6]

#łączymy ramek danych - odpowiednik union all w sql
df1_2 = pd.concat([df1, df2])
print("df1")
print(df1)
print("df2")
print(df2)
print("df1_2")
print(df1_2)

#łączenie ramek danych - odpowiednik join w sql
df_ext = pd.DataFrame.from_records([(18.0, "A"), (0.0, "B")], columns = ["ZN", "ZN_desc"])

print("df_ext")
print(df_ext)


print("df1_2 left join df_ext")
print(df1_2.merge(df_ext, how ="left")) #domyślnie łączy po kolumnach o takich samych nazwach, w parametrach on, left_on, right_on można podać po jakich kolumnach ma się odbyć łączenie

/usr/local/lib/python3.6/dist-packages/sklearn/datasets/data/boston_house_prices.csv
df1
      CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7

[3 rows x 14 columns]
df2
      CRIM   ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
3  0.03237  0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905  0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
5  0.02985  0.0   2.18     0  0.458  ...  222     18.7  394.12   5.21  28.7

[3 rows x 14 columns]
df1_2
      CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
5  0.02985   0.0   2.18     0  0.458  ...  222     18.7  394.12   5.21  28.7

[6 rows x 14 columns]
df_ext
     ZN ZN_desc
0  18.0       A
1   0.0       B
df1_2 left join df_ext
      CRIM    ZN  INDUS  CHAS    NOX  ...  PTRATIO       B  LSTAT  MEDV  ZN_desc
0  0.00632  18.0   2.31     0  0.538  ...     15.3  396.90   4.98  24.0        A
1  0.02731   0.0   7.07     0  0.469  ...     17.8  396.90   9.14  21.6        B
2  0.02729   0.0   7.07     0  0.469  ...     17.8  392.83   4.03  34.7        B
3  0.03237   0.0   2.18     0  0.458  ...     18.7  394.63   2.94  33.4        B
4  0.06905   0.0   2.18     0  0.458  ...     18.7  396.90   5.33  36.2        B
5  0.02985   0.0   2.18     0  0.458  ...     18.7  394.12   5.21  28.7        B

[6 rows x 15 columns]

# 3 Seria a DataFrame

## 3.1 Seria

### 3.1.2 Atrybuty

1. .size - rozmiar w pamięci

In [0]:
df1.size

5622900

2. .nbytes - ilość bytów dla Serii (inaczek kolumny). Dlatego najpierw definiuje serie

In [0]:
seria=df1['name']
seria.nbytes

2998880

3. .is_unique - czy posiada dana seria unikalne wartości

In [0]:
seria.is_unique

False

4. .is_monotonic - monotoniczne lub posortowane

In [0]:
seria.is_monotonic

False

5. .index - budowa indexu

In [0]:
df1.index

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            378651, 378652, 378653, 378654, 378655, 378656, 378657, 378658,
            378659, 378660],
           dtype='int64', length=374860)

6. .values - jakie wartości

In [0]:
seria.values

array(['The Songs of Adelaide & Abullah',
       'Greeting From Earth: ZGAC Arts Capsule For ET', 'Where is Hank?',
       ...,
       'Walls of Remedy- New lesbian Romantic Comedy feature unlike any other!!',
       'BioDefense Education Kit', 'Nou Renmen Ayiti!  We Love Haiti!'],
      dtype=object)

7. .dtype - jakiego typu są kolumny

In [0]:
df1.dtypes

ID                    int64
name                 object
category             object
main_category        object
currency             object
deadline             object
goal                float64
launched             object
pledged             float64
state                object
backers               int64
country              object
usd pledged         float64
usd_pledged_real    float64
usd_goal_real       float64
dtype: object

8. .shape - kształt

In [0]:
df1.shape

(374860, 15)

9. .axes - współrzędne

In [0]:
df1.axes

[Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                  8,      9,
             ...
             378651, 378652, 378653, 378654, 378655, 378656, 378657, 378658,
             378659, 378660],
            dtype='int64', length=374860),
 Index(['ID', 'name', 'category', 'main_category', 'currency', 'deadline',
        'goal', 'launched', 'pledged', 'state', 'backers', 'country',
        'usd pledged', 'usd_pledged_real', 'usd_goal_real'],
       dtype='object')]

### 3.1.3 Metody

1. .sum()

In [0]:
seriaM=df1['ID']
seriaM.sum()

402844181999705

2. seriaM.min()

In [0]:
seriaM.min()

5971

3. .max()

In [0]:
seriaM.max()

2147476221

4. .count()

In [0]:
seriaM.count()

374860

5. .size

In [0]:
seriaM.size

374860

6. .product - wymnarza wszystko przez siebie i zwraca wynik, jakiś taki iloczyn kartezjański

In [0]:
seriaM.product

<bound method Series.prod of 0         1000002330
1         1000003930
2         1000004038
3         1000007540
4         1000011046
5         1000014025
6         1000023410
7         1000030581
8         1000034518
9          100004195
10         100004721
11         100005484
12        1000055792
13        1000056157
14        1000057089
15        1000064368
16        1000064918
17        1000068480
18        1000070642
19        1000071625
20        1000072011
21        1000081649
22        1000082254
23        1000087442
24        1000091520
25        1000102741
26        1000103948
27        1000104688
28        1000104953
29         100011318
             ...
378631     999832803
378632      99984851
378633     999865831
378634     999867839
378635      99987261
378636     999877902
378637     999878813
378638     999880710
378639     999884445
378640     999893629
378641      99991751
378642     999929142
378643     999931480
378644     999934908
378645     999941823
378646     999943841
378647     999950812
378648     999955533
378649     999963618
378650      99996661
378651     999969812
378652     999971898
378653     999972264
378654     999975836
378655     999976312
378656     999976400
378657     999977640
378658     999986353
378659     999987933
378660     999988282
Name: ID, Length: 374860, dtype: int64>

7. .keys()

In [0]:
seriaM.keys()

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            378651, 378652, 378653, 378654, 378655, 378656, 378657, 378658,
            378659, 378660],
           dtype='int64', length=374860)

8. .get_values

In [0]:
seriaM.get_values

<bound method Series.get_values of 0         1000002330
1         1000003930
2         1000004038
3         1000007540
4         1000011046
5         1000014025
6         1000023410
7         1000030581
8         1000034518
9          100004195
10         100004721
11         100005484
12        1000055792
13        1000056157
14        1000057089
15        1000064368
16        1000064918
17        1000068480
18        1000070642
19        1000071625
20        1000072011
21        1000081649
22        1000082254
23        1000087442
24        1000091520
25        1000102741
26        1000103948
27        1000104688
28        1000104953
29         100011318
             ...
378631     999832803
378632      99984851
378633     999865831
378634     999867839
378635      99987261
378636     999877902
378637     999878813
378638     999880710
378639     999884445
378640     999893629
378641      99991751
378642     999929142
378643     999931480
378644     999934908
378645     999941823
378646     999943841
378647     999950812
378648     999955533
378649     999963618
378650      99996661
378651     999969812
378652     999971898
378653     999972264
378654     999975836
378655     999976312
378656     999976400
378657     999977640
378658     999986353
378659     999987933
378660     999988282
Name: ID, Length: 374860, dtype: int64>

9. .tolist() - przekształcenie SERIES do Listy!!!

In [0]:
seriaM.to_list()

[1000002330,
 1000003930,
 1000004038,
 1000007540,
 1000011046,
 1000014025,
 1000023410,
 1000030581,
 1000034518,
 100004195,
 100004721,
 100005484,
 1000055792,
 1000056157,
 1000057089,
 1000064368,
 1000064918,
 1000068480,
 1000070642,
 1000071625,
 1000072011,
 1000081649,
 1000082254,
 1000087442,
 1000091520,
 1000102741,
 1000103948,
 1000104688,
 1000104953,
 100011318,
 1000115172,
 1000117861,
 1000120151,
 1000120287,
 100012079,
 1000129669,
 1000131947,
 1000132945,
 1000134913,
 1000146991,
 1000149007,
 1000153208,
 1000160286,
 1000170964,
 1000171141,
 1000182258,
 1000183112,
 1000184224,
 1000190427,
 1000197321,
 1000201265,
 100020143,
 1000202062,
 1000212914,
 1000216800,
 1000217634,
 1000226576,
 1000227361,
 1000230071,
 1000232288,
 1000233415,
 1000234595,
 1000235465,
 1000235643,
 1000243793,
 1000245024,
 1000252415,
 1000256230,
 1000256760,
 1000257563,
 1000260691,
 1000261018,
 1000268182,
 1000278154,
 1000282287,
 1000291122,
 1000291263,
 1000294559,
 1000320473,
 1000328150,
 1000328328,
 1000331311,
 1000332383,
 1000333671,
 1000334074,
 1000335422,
 1000338818,
 1000339877,
 1000340977,
 1000344383,
 1000348690,
 1000348776,
 1000354338,
 10003650,
 1000374001,
 1000386601,
 1000389241,
 1000392220,
 100039820,
 1000399155,
 1000405957,
 1000413719,
 1000415969,
 1000422671,
 1000427280,
 1000428719,
 10004373,
 100044420,
 1000445513,
 1000450327,
 1000454605,
 1000465399,
 1000468345,
 1000476123,
 1000479996,
 1000481607,
 1000490852,
 1000491057,
 1000491830,
 1000499845,
 1000509854,
 1000514796,
 100051531,
 1000519001,
 1000521061,
 1000521421,
 1000524949,
 1000535116,
 1000537760,
 1000542390,
 1000543883,
 1000545028,
 1000549881,
 1000551777,
 1000553538,
 1000558429,
 1000566862,
 1000567557,
 100056789,
 100057323,
 1000577059,
 10005784,
 1000581546,
 1000581804,
 1000586849,
 1000590709,
 1000598804,
 1000600012,
 1000600526,
 1000600868,
 1000602156,
 1000620551,
 1000624031,
 1000627718,
 1000629643,
 1000638156,
 1000639526,
 1000644119,
 1000648117,
 1000648918,
 100065084,
 1000650960,
 1000654344,
 1000654409,
 1000656794,
 1000659557,
 1000674477,
 1000682368,
 1000684975,
 1000697657,
 1000699196,
 1000707541,
 1000710630,
 1000719127,
 1000725978,
 1000727191,
 1000727905,
 1000741180,
 1000741387,
 1000752960,
 1000754401,
 1000758916,
 1000761521,
 1000767040,
 1000770149,
 1000772297,
 1000776914,
 1000777557,
 1000781363,
 1000781512,
 1000785030,
 1000786724,
 1000788629,
 100078996,
 1000802137,
 1000804307,
 1000804742,
 1000810416,
 1000811882,
 1000823935,
 1000827504,
 1000827890,
 1000834930,
 1000844246,
 1000850525,
 1000853310,
 1000865260,
 1000869383,
 1000883509,
 1000885772,
 100089599,
 1000896053,
 1000916036,
 1000918505,
 100091944,
 1000922108,
 1000932522,
 1000937140,
 1000940032,
 1000942804,
 1000953875,
 1000968500,
 1000983983,
 1000987760,
 1000988678,
 1000988864,
 1000992739,
 1000997384,
 1001000566,
 100101389,
 100101652,
 1001019464,
 1001020080,
 100102338,
 1001028167,
 1001033266,
 1001035783,
 1001042227,
 1001043181,
 1001048123,
 1001052357,
 1001057158,
 1001064677,
 1001077166,
 1001086968,
 1001087429,
 1001087682,
 1001093391,
 1001097057,
 1001110351,
 1001115961,
 1001116225,
 1001126692,
 1001128468,
 1001132597,
 1001135664,
 1001136944,
 1001137002,
 1001143049,
 1001149306,
 100114978,
 1001156528,
 1001157858,
 1001159174,
 1001165113,
 10011702,
 1001181420,
 1001188527,
 1001190550,
 1001216413,
 1001217929,
 1001218320,
 1001223817,
 1001227372,
 1001228129,
 1001230250,
 1001242672,
 1001243185,
 1001243867,
 1001244864,
 100124630,
 1001251896,
 1001259618,
 1001263250,
 1001265769,
 1001270191,
 1001279854,
 1001288451,
 1001292387,
 1001295591,
 100130008,
 1001302417,
 1001302832,
 1001303993,
 1001304256,
 1001328623,
 1001333672,
 1001338336,
 1001338443,
 1001339505,
 1001340544,
 100134337,
 1001344493,
 1001347176,
 1001348491,
 1001352451,
 1001353002,
 1001353112,
 1001366443,
 1001368898,
 1001373564,
 1001377540,
 1001404128,
 1001407622,
 1001423755,
 1001432466,
 1001435839,
 1001442355,
 1001442379,
 100144828,
 1001468086,
 100147142,
 1001473842,
 1001476723,
 1001484182,
 1001490622,
 1001494526,
 1001498884,
 1001502333,
 1001503577,
 1001508135,
 1001513743,
 1001516983,
 1001523858,
 1001524172,
 1001527526,
 1001529115,
 1001529854,
 1001542282,
 1001543887,
 1001548662,
 1001556760,
 1001560762,
 1001565620,
 1001566226,
 1001567779,
 1001570537,
 1001573862,
 1001575705,
 1001576108,
 1001578248,
 100158537,
 1001591110,
 1001600663,
 100161658,
 100162622,
 1001639879,
 1001639910,
 1001650469,
 1001656127,
 1001664105,
 1001685760,
 1001687258,
 1001689284,
 1001696224,
 1001704257,
 1001708060,
 100171056,
 1001711592,
 1001714289,
 1001723373,
 1001726950,
 1001732009,
 100173367,
 100173829,
 1001751835,
 1001762923,
 1001768094,
 1001778275,
 1001780885,
 1001786083,
 1001787855,
 1001796633,
 100181036,
 1001813414,
 1001814122,
 1001817414,
 1001820357,
 100182282,
 1001823329,
 10018239,
 1001838811,
 1001839289,
 1001842762,
 1001846249,
 1001856035,
 1001857288,
 1001863639,
 1001878319,
 100188605,
 1001892879,
 1001899204,
 1001904214,
 1001904397,
 1001916592,
 1001923268,
 1001924624,
 100194308,
 1001951313,
 100196479,
 1001967967,
 1001973436,
 1001975568,
 1001979324,
 1001981525,
 1001988165,
 1001989065,
 1001991458,
 1001994928,
 1002004487,
 1002005884,
 1002007289,
 1002027893,
 1002029488,
 1002031061,
 1002042898,
 1002045558,
 1002058532,
 1002058739,
 1002071867,
 100207951,
 1002085616,
 1002087593,
 1002089437,
 1002096459,
 1002098978,
 1002100913,
 1002105969,
 1002109548,
 1002117681,
 1002117994,
 100212057,
 1002122038,
 1002125056,
 1002125164,
 100212849,
 1002131859,
 1002132449,
 1002132537,
 1002133517,
 1002139381,
 1002139540,
 1002140523,
 1002151750,
 1002181673,
 1002182970,
 1002183790,
 1002187988,
 1002189572,
 1002191351,
 1002191592,
 1002193030,
 1002193523,
 1002208176,
 1002211518,
 1002222234,
 1002222363,
 1002226766,
 1002234028,
 100224840,
 1002250421,
 1002264833,
 1002269200,
 1002272545,
 100227845,
 1002287054,
 1002289150,
 1002294238,
 1002295749,
 1002299677,
 1002304874,
 100230798,
 1002308373,
 1002312219,
 1002342607,
 1002344676,
 1002355670,
 1002363227,
 100236770,
 1002368838,
 1002371950,
 1002372799,
 1002379225,
 1002382304,
 1002383422,
 1002384825,
 1002388106,
 1002400187,
 1002405311,
 1002407161,
 1002416983,
 1002418598,
 10024216,
 1002421792,
 1002436709,
 1002444966,
 100245014,
 1002451969,
 1002453633,
 1002455585,
 1002456171,
 1002478333,
 1002484986,
 1002490303,
 1002492289,
 10024998,
 1002500521,
 1002511877,
 1002512911,
 1002514543,
 1002515281,
 1002519316,
 1002520944,
 1002521611,
 1002522073,
 1002524565,
 1002538085,
 1002554777,
 1002560995,
 1002570423,
 1002571103,
 1002585330,
 1002586292,
 1002590077,
 1002597730,
 1002599057,
 1002599773,
 1002599863,
 1002611685,
 1002617687,
 1002621189,
 1002624093,
 1002629894,
 100263139,
 1002633138,
 100264379,
 1002646104,
 1002646572,
 1002651584,
 1002664274,
 1002674727,
 1002681356,
 1002684709,
 1002692211,
 1002710067,
 1002715554,
 1002717273,
 1002717707,
 1002720451,
 1002721954,
 1002723323,
 1002723555,
 1002724533,
 1002728217,
 1002734991,
 1002740336,
 1002745522,
 1002746950,
 1002749658,
 100275914,
 1002762500,
 1002767552,
 1002768509,
 1002770238,
 1002772966,
 1002777672,
 1002780789,
 1002783462,
 100278912,
 1002789295,
 1002789956,
 1002799755,
 1002810193,
 1002812438,
 100281397,
 1002835689,
 1002840021,
 1002843911,
 1002854072,
 1002854457,
 1002856989,
 1002857267,
 1002864290,
 1002868550,
 1002877175,
 1002884058,
 1002884302,
 1002885178,
 1002886944,
 1002894446,
 1002899845,
 1002904556,
 1002907198,
 1002909435,
 1002910237,
 1002911532,
 1002914380,
 1002919742,
 1002933346,
 1002937987,
 1002938908,
 1002939824,
 1002944526,
 1002946462,
 1002957206,
 1002958908,
 1002959927,
 1002965096,
 1002966619,
 100296818,
 1002981465,
 1002984666,
 1002985353,
 1002987150,
 1002997533,
 100301082,
 1003011722,
 100301303,
 1003014108,
 100301891,
 1003036680,
 1003053633,
 1003074300,
 1003074363,
 1003075861,
 1003083361,
 1003087682,
 1003095315,
 1003104071,
 1003111955,
 1003118035,
 1003122437,
 1003125430,
 1003127225,
 1003138593,
 10031522,
 1003155427,
 1003165056,
 1003166589,
 1003167050,
 1003169165,
 1003182869,
 1003189373,
 1003190758,
 1003202814,
 1003216930,
 1003217096,
 1003228594,
 1003229159,
 100324011,
 1003240719,
 1003249516,
 1003259197,
 1003262687,
 1003276918,
 1003279532,
 100328540,
 1003293246,
 1003294350,
 1003298216,
 1003308182,
 1003312804,
 1003329858,
 1003330319,
 1003338175,
 1003343308,
 1003346672,
 1003353231,
 1003356565,
 1003357844,
 1003362350,
 1003362537,
 1003365384,
 1003366986,
 1003367610,
 1003378025,
 1003381,
 1003405223,
 1003413226,
 1003413796,
 100341575,
 1003424923,
 100343348,
 1003434687,
 1003436789,
 1003441266,
 1003442902,
 1003447204,
 1003449040,
 1003456090,
 1003458038,
 1003458646,
 1003462608,
 10034684,
 1003478705,
 1003480324,
 1003481542,
 1003481744,
 10034874,
 1003490202,
 1003490559,
 100349058,
 1003494681,
 1003497710,
 1003499986,
 1003500295,
 1003500859,
 1003503289,
 1003506524,
 1003506965,
 1003509297,
 1003514666,
 1003515712,
 1003521001,
 1003523496,
 1003523631,
 1003523647,
 1003525413,
 1003533888,
 1003538517,
 1003539829,
 1003548564,
 1003558634,
 1003560849,
 1003561048,
 1003561611,
 1003568124,
 1003570206,
 1003572906,
 1003583457,
 1003583595,
 100358406,
 100359228,
 1003596506,
 1003616594,
 1003637092,
 100365021,
 1003665581,
 1003666213,
 1003666645,
 1003666946,
 1003674692,
 1003677068,
 1003708660,
 1003709180,
 100371737,
 1003723279,
 1003725305,
 1003727338,
 100372771,
 1003742402,
 1003743392,
 100375774,
 1003757970,
 1003760463,
 1003761602,
 1003769496,
 1003770739,
 1003775701,
 1003775790,
 1003778636,
 1003793542,
 1003794504,
 100379732,
 1003801298,
 1003804028,
 1003804552,
 1003813966,
 1003819770,
 1003829191,
 1003830843,
 1003832819,
 1003835559,
 100385010,
 1003851620,
 1003856570,
 1003865687,
 1003865949,
 1003868419,
 1003884132,
 1003886618,
 1003889504,
 1003899141,
 1003900292,
 1003901425,
 1003904501,
 1003906010,
 1003909472,
 1003928652,
 1003928906,
 1003933374,
 1003938077,
 1003940608,
 1003946946,
 1003953048,
 1003953996,
 1003957942,
 100395799,
 1003960110,
 100396408,
 1003967599,
 1003973953,
 1003974659,
 1003983201,
 1003990867,
 100399282,
 1003997707,
 1004008910,
 1004010327,
 1004015081,
 1004020983,
 1004025520,
 1004027294,
 1004030065,
 1004065093,
 1004070621,
 1004080416,
 10040833,
 1004084377,
 1004088982,
 1004091259,
 1004094650,
 1004097002,
 1004098791,
 1004109096,
 1004112120,
 100411349,
 1004125151,
 1004126907,
 100413062,
 1004131124,
 1004138236,
 1004152737,
 1004156743,
 1004167304,
 1004189486,
 1004192678,
 1004198028,
 1004203496,
 1004211205,
 1004216021,
 1004218067,
 1004220301,
 1004220332,
 1004226383,
 1004236435,
 1004249231,
 1004261287,
 1004269025,
 1004275298,
 1004275497,
 1004286651,
 1004303528,
 1004304382,
 1004304591,
 1004307461,
 1004307530,
 1004317441,
 100433895,
 1004339642,
 1004349656,
 1004353925,
 1004356539,
 1004367374,
 100437007,
 1004372197,
 1004377000,
 1004379805,
 100438743,
 1004394288,
 1004399460,
 1004405723,
 1004405919,
 10044110,
 1004434782,
 1004436383,
 1004448951,
 1004451940,
 1004456764,
 1004457833,
 1004458643,
 1004468122,
 1004473432,
 1004480789,
 100448936,
 1004493837,
 1004500333,
 1004506986,
 1004511073,
 1004513718,
 1004516410,
 100452386,
 1004551323,
 100455559,
 1004559427,
 1004560254,
 1004597770,
 1004598628,
 1004598691,
 100459896,
 100459984,
 1004600408,
 1004619032,
 1004621325,
 1004621740,
 1004637630,
 1004638242,
 1004641424,
 100464296,
 1004648273,
 1004649506,
 1004666737,
 1004668657,
 1004671073,
 1004671876,
 1004686676,
 1004687584,
 1004692921,
 1004696424,
 1004697378,
 1004698783,
 1004727949,
 1004749427,
 1004752143,
 1004756907,
 1004760459,
 1004763680,
 1004766153,
 1004781384,
 1004783664,
 1004784584,
 1004807406,
 1004808301,
 1004812579,
 1004814701,
 1004814890,
 1004817817,
 1004820376,
 1004830984,
 100483818,
 1004846489,
 1004851582,
 1004856971,
 1004859669,
 1004866875,
 1004871321,
 1004889267,
 1004911835,
 1004921259,
 1004922401,
 1004930345,
 1004941506,
 100495978,
 1004959988,
 1004964278,
 1004968643,
 1004972393,
 1004979544,
 100497966,
 1004982490,
 1004988635,
 1004989778,
 1004990910,
 1004999687,
 1005000674,
 10050058,
 1005008262,
 1005009188,
 1005014904,
 1005018489,
 1005020458,
 1005023399,
 1005027414,
 1005030157,
 1005036020,
 1005037455,
 1005040851,
 1005044737,
 1005051188,
 1005053619,
 1005063605,
 1005072084,
 1005072752,
 1005080604,
 1005081073,
 1005097329,
 1005100517,
 100510248,
 1005103612,
 1005115850,
 ...]

10. .add(10) - dodanie 10 do każdego elementu Series

In [0]:
seriaM.add(10)

0         1000002340
1         1000003940
2         1000004048
3         1000007550
4         1000011056
5         1000014035
6         1000023420
7         1000030591
8         1000034528
9          100004205
10         100004731
11         100005494
12        1000055802
13        1000056167
14        1000057099
15        1000064378
16        1000064928
17        1000068490
18        1000070652
19        1000071635
20        1000072021
21        1000081659
22        1000082264
23        1000087452
24        1000091530
25        1000102751
26        1000103958
27        1000104698
28        1000104963
29         100011328
             ...
378631     999832813
378632      99984861
378633     999865841
378634     999867849
378635      99987271
378636     999877912
378637     999878823
378638     999880720
378639     999884455
378640     999893639
378641      99991761
378642     999929152
378643     999931490
378644     999934918
378645     999941833
378646     999943851
378647     999950822
378648     999955543
378649     999963628
378650      99996671
378651     999969822
378652     999971908
378653     999972274
378654     999975846
378655     999976322
378656     999976410
378657     999977650
378658     999986363
378659     999987943
378660     999988292
Name: ID, Length: 374860, dtype: int64

11. .reindex() - przebudowywanie indexu, można też zastąpić tą metodą NULLe parametrem **fill_value**

In [0]:
seriaM.reindex(index=None).head()

0    1000002330
1    1000003930
2    1000004038
3    1000007540
4    1000011046
Name: ID, dtype: int64

12. .str.upper() - na duże litery

In [0]:
seriaText=df1['category']
seriaText.str.upper()

0                   POETRY
1           NARRATIVE FILM
2           NARRATIVE FILM
3                    MUSIC
4             FILM & VIDEO
5              RESTAURANTS
6                     FOOD
7                   DRINKS
8           PRODUCT DESIGN
9              DOCUMENTARY
10              NONFICTION
11              INDIE ROCK
12                  CRAFTS
13                   GAMES
14          TABLETOP GAMES
15                  DESIGN
16             COMIC BOOKS
17               ART BOOKS
18                   MUSIC
19                    FOOD
20                 FASHION
21           CHILDRENSWEAR
22                 THEATER
23                  DRINKS
24                  COMICS
25                   MUSIC
26                     DIY
27               WEBSERIES
28                  COMICS
29               ANIMATION
                ...
378631       PLAYING CARDS
378632              COMEDY
378633             APPAREL
378634         PHOTOGRAPHY
378635          NONFICTION
378636      COUNTRY & FOLK
378637              SHORTS
378638          NONFICTION
378639              DRINKS
378640             FICTION
378641      PRODUCT DESIGN
378642      TABLETOP GAMES
378643         3D PRINTING
378644      PRODUCT DESIGN
378645              COMICS
378646    CHILDREN'S BOOKS
378647          NONFICTION
378648      TABLETOP GAMES
378649      NARRATIVE FILM
378650                APPS
378651     CLASSICAL MUSIC
378652         DOCUMENTARY
378653         DOCUMENTARY
378654         SMALL BATCH
378655              POETRY
378656         DOCUMENTARY
378657      NARRATIVE FILM
378658      NARRATIVE FILM
378659          TECHNOLOGY
378660     PERFORMANCE ART
Name: category, Length: 374860, dtype: object

13. .map() - mapowanie serii lub słownika na przykładzie z wbudowanego helpa

In [0]:
s = pd.Series(['cat', 'dog', np.nan, 'rabbit'])
print(s)
s.map({'cat': 'kitten', 'dog': 'puppy'})

0       cat
1       dog
2       NaN
3    rabbit
dtype: object

0    kitten
1     puppy
2       NaN
3       NaN
dtype: object

14. .get_dtype_counts() - zlicza ilość kolumn danego typu

In [0]:
df1.get_dtype_counts()

float64    5
int64      2
object     8
dtype: int64

15. .value_counts() - ile jest poszczególnych wartości

In [0]:
seriaText.value_counts()

Product Design       22310
Documentary          16138
Tabletop Games       14178
Music                13340
Shorts               12357
Video Games          11828
Food                 11492
Film & Video          9224
Fiction               9168
Fashion               8554
Nonfiction            8317
Art                   8253
Apparel               7165
Theater               7056
Technology            6927
Rock                  6758
Children's Books      6756
Apps                  6345
Webseries             5762
Photography           5752
Indie Rock            5657
Publishing            5525
Narrative Film        5186
Web                   5153
Comics                4996
Crafts                4664
Country & Folk        4451
Design                4199
Hip-Hop               3911
Hardware              3662
                     ...
Couture                275
Blues                  268
Animals                255
Fabrication Tools      250
Makerspaces            238
Printing               238
Movie Theaters         232
Puzzles                231
Bacon                  221
Stationery             219
Photo                  196
Video Art              194
Romance                190
Knitting               181
Workshops              164
Crochet                162
Translations           153
Pet Fashion            139
Glass                  138
Latin                  137
Embroidery             113
Typography             108
Pottery                100
Weaving                 93
Quilts                  81
Residencies             69
Letterpress             49
Chiptune                35
Literary Spaces         27
Taxidermy               13
Name: category, Length: 159, dtype: int64

16. .sample() - losowanie kilku wartości - taki random

In [0]:
seriaText.sample(5)

119377          Games
144126    Anthologies
117732          Sound
73238         Fiction
158262    World Music
Name: category, dtype: object

17. .copy() - kopiowanie rammki danych, używamy aby działać na kopii i nie wywalić głównego zbioru

In [0]:
seriaNowa=seriaText.copy()
seriaNowa

0                   Poetry
1           Narrative Film
2           Narrative Film
3                    Music
4             Film & Video
5              Restaurants
6                     Food
7                   Drinks
8           Product Design
9              Documentary
10              Nonfiction
11              Indie Rock
12                  Crafts
13                   Games
14          Tabletop Games
15                  Design
16             Comic Books
17               Art Books
18                   Music
19                    Food
20                 Fashion
21           Childrenswear
22                 Theater
23                  Drinks
24                  Comics
25                   Music
26                     DIY
27               Webseries
28                  Comics
29               Animation
                ...
378631       Playing Cards
378632              Comedy
378633             Apparel
378634         Photography
378635          Nonfiction
378636      Country & Folk
378637              Shorts
378638          Nonfiction
378639              Drinks
378640             Fiction
378641      Product Design
378642      Tabletop Games
378643         3D Printing
378644      Product Design
378645              Comics
378646    Children's Books
378647          Nonfiction
378648      Tabletop Games
378649      Narrative Film
378650                Apps
378651     Classical Music
378652         Documentary
378653         Documentary
378654         Small Batch
378655              Poetry
378656         Documentary
378657      Narrative Film
378658      Narrative Film
378659          Technology
378660     Performance Art
Name: category, Length: 374860, dtype: object

18. .str.endswith('xxx') - spradza czy komórka kończy się xxx

In [0]:
seria.str.endswith('xxx')

0         False
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...
378631    False
378632    False
378633    False
378634    False
378635    False
378636    False
378637    False
378638    False
378639    False
378640    False
378641    False
378642    False
378643    False
378644    False
378645    False
378646    False
378647    False
378648    False
378649    False
378650    False
378651    False
378652    False
378653    False
378654    False
378655    False
378656    False
378657    False
378658    False
378659    False
378660    False
Name: name, Length: 374860, dtype: bool

19. .str.strip() - ucina na początku i końću białe znaki w tym spacje

In [0]:
seria.str.strip()

0                           The Songs of Adelaide & Abullah
1             Greeting From Earth: ZGAC Arts Capsule For ET
2                                            Where is Hank?
3         ToshiCapital Rekordz Needs Help to Complete Album
4         Community Film Project: The Art of Neighborhoo...
5                                      Monarch Espresso Bar
6         Support Solar Roasted Coffee & Green Energy!  ...
7         Chaser Strips. Our Strips make Shots their B*tch!
8         SPIN - Premium Retractable In-Ear Headphones w...
9         STUDIO IN THE SKY - A Documentary Feature Film...
10                                      Of Jesus and Madmen
11                                         Lisa Lim New CD!
12                                       The Cottage Market
13        G-Spot Place for Gamers to connect with eachot...
14        Tombstone: Old West tabletop game and miniatur...
15                                           Survival Rings
16                                                The Beard
17                         Notes From London: Above & Below
18                      Mike Corey's Darkness & Light Album
19                                                 Boco Tea
20                    CMUK. Shoes: Take on Life Feet First.
21                         MikeyJ clothing brand fundraiser
22                           Alice in Wonderland in G Minor
23        Mountain brew: A quest for alcohol sustainability
24                              The Book Zoo - A Mini-Comic
25        Matt Cavenaugh & Jenny Powers make their 1st a...
26                                     Superhero Teddy Bear
27                                      Permaculture Skills
28        Rebel Army Origins: The Heroic Story Of Major ...
29                            My Moon - Animated Short Film
                                ...
378631    MONSTROCARDS- A Creative Drawing Game of Horri...
378632                                             "Loreto"
378633    STATE OF G - Men's Blazer Jacket & Women's Car...
378634                                        Transcaucasia
378635    You're Not Cis, You Just Think You Are: My Enb...
378636                        Little Saturday's Debut Album
378637                             Ways to Look at the Moon
378638                                  Terminal Uniqueness
378639    Superette Tea - Boldly Caffeinated Loose Leaf Tea
378640                            Ciridian Helix (Canceled)
378641     Here is the oasis for the youngest in the world.
378642    ÉPOUVANTAILS : 28mm Figurines de jeux pour KIN...
378643                       Google Glass Shield (Canceled)
378644                                 The Manual Bar Blade
378645          The Chronicles of Erinoth - A Graphic Novel
378646                                  The Dog Coffee Book
378647                                The Cease is Increase
378648          Cards and Chit Network Season 2! (Canceled)
378649        Colorado International Activism Film Festival
378650                           Date Seat - Boston iOS App
378651                                         AT THE BEACH
378652                          Beach Wrestling Documentary
378653                                              Islanda
378654                Homemade fresh dog food, Cleveland OH
378655                           Angela's Poetry (Canceled)
378656    ChknTruk Nationwide Charity Drive 2014 (Canceled)
378657                                            The Tribe
378658    Walls of Remedy- New lesbian Romantic Comedy f...
378659                             BioDefense Education Kit
378660                    Nou Renmen Ayiti!  We Love Haiti!
Name: name, Length: 374860, dtype: object

20. .str.split(' ') - potnie po spacji

In [0]:
seria.str.split(' ')

0                    [The, Songs, of, Adelaide, &, Abullah]
1         [Greeting, From, Earth:, ZGAC, Arts, Capsule, ...
2                                        [Where, is, Hank?]
3         [ToshiCapital, Rekordz, Needs, Help, to, Compl...
4         [Community, Film, Project:, The, Art, of, Neig...
5                                  [Monarch, Espresso, Bar]
6         [Support, Solar, Roasted, Coffee, &, Green, En...
7         [Chaser, Strips., Our, Strips, make, Shots, th...
8         [SPIN, -, Premium, Retractable, In-Ear, Headph...
9         [STUDIO, IN, THE, SKY, -, A, Documentary, Feat...
10                                 [Of, Jesus, and, Madmen]
11                                    [Lisa, Lim, New, CD!]
12                                   [The, Cottage, Market]
13        [G-Spot, Place, for, Gamers, to, connect, with...
14        [Tombstone:, Old, West, tabletop, game, and, m...
15                                        [Survival, Rings]
16                                             [The, Beard]
17                  [Notes, From, London:, Above, &, Below]
18               [Mike, Corey's, Darkness, &, Light, Album]
19                                              [Boco, Tea]
20            [CMUK., Shoes:, Take, on, Life, Feet, First.]
21                    [MikeyJ, clothing, brand, fundraiser]
22                    [Alice, in, Wonderland, in, G, Minor]
23        [Mountain, brew:, A, quest, for, alcohol, sust...
24                       [The, Book, Zoo, -, A, Mini-Comic]
25        [Matt, Cavenaugh, &, Jenny, Powers, make, thei...
26                                 [Superhero, Teddy, Bear]
27                                   [Permaculture, Skills]
28        [Rebel, Army, Origins:, The, Heroic, Story, Of...
29                     [My, Moon, -, Animated, Short, Film]
                                ...
378631    [MONSTROCARDS-, A, Creative, Drawing, Game, of...
378632                                           ["Loreto"]
378633    [STATE, OF, G, -, Men's, Blazer, Jacket, &, Wo...
378634                                      [Transcaucasia]
378635    [You're, Not, Cis,, You, Just, Think, You, Are...
378636                   [Little, Saturday's, Debut, Album]
378637                      [Ways, to, Look, at, the, Moon]
378638                               [Terminal, Uniqueness]
378639    [Superette, Tea, -, Boldly, Caffeinated, Loose...
378640                        [Ciridian, Helix, (Canceled)]
378641    [Here, is, the, oasis, for, the, youngest, in,...
378642    [ÉPOUVANTAILS, :, 28mm, Figurines, de, jeux, p...
378643                  [Google, Glass, Shield, (Canceled)]
378644                            [The, Manual, Bar, Blade]
378645    [The, Chronicles, of, Erinoth, -, A, Graphic, ...
378646                             [The, Dog, Coffee, Book]
378647                           [The, Cease, is, Increase]
378648    [Cards, and, Chit, Network, Season, 2!, (Cance...
378649    [Colorado, International, Activism, Film, Fest...
378650                    [Date, Seat, -, Boston, iOS, App]
378651                                     [AT, THE, BEACH]
378652                      [Beach, Wrestling, Documentary]
378653                                            [Islanda]
378654         [Homemade, fresh, dog, food,, Cleveland, OH]
378655                       [Angela's, Poetry, (Canceled)]
378656    [ChknTruk, Nationwide, Charity, Drive, 2014, (...
378657                                         [The, Tribe]
378658    [Walls, of, Remedy-, New, lesbian, Romantic, C...
378659                         [BioDefense, Education, Kit]
378660            [Nou, Renmen, Ayiti!, , We, Love, Haiti!]
Name: name, Length: 374860, dtype: object

21. .str.split(' ',expand=True) - potnie po spacji i podzieli na kolumny

In [0]:
seria.str.split(' ',expand=True)

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,The,Songs,of,Adelaide,&,Abullah,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,Greeting,From,Earth:,ZGAC,Arts,Capsule,For,ET,None,None,...,None,None,None,None,None,None,None,None,None,None
2,Where,is,Hank?,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,ToshiCapital,Rekordz,Needs,Help,to,Complete,Album,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,Community,Film,Project:,The,Art,of,Neighborhood,Filmmaking,None,None,...,None,None,None,None,None,None,None,None,None,None
5,Monarch,Espresso,Bar,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
6,Support,Solar,Roasted,Coffee,&,Green,Energy!,,SolarCoffee.co,None,...,None,None,None,None,None,None,None,None,None,None
7,Chaser,Strips.,Our,Strips,make,Shots,their,B*tch!,None,None,...,None,None,None,None,None,None,None,None,None,None
8,SPIN,-,Premium,Retractable,In-Ear,Headphones,with,Mic,None,None,...,None,None,None,None,None,None,None,None,None,None
9,STUDIO,IN,THE,SKY,-,A,Documentary,Feature,Film,(Canceled),...,None,None,None,None,None,None,None,None,None,None
10,Of,Jesus,and,Madmen,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
11,Lisa,Lim,New,CD!,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
12,The,Cottage,Market,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
13,G-Spot,Place,for,Gamers,to,connect,with,eachother,&,go,...,None,None,None,None,None,None,None,None,None,None
14,Tombstone:,Old,West,tabletop,game,and,miniatures,in,32mm.,None,...,None,None,None,None,None,None,None,None,None,None
15,Survival,Rings,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
16,The,Beard,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
17,Notes,From,London:,Above,&,Below,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
18,Mike,Corey's,Darkness,&,Light,Album,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
19,Boco,Tea,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
20,CMUK.,Shoes:,Take,on,Life,Feet,First.,None,None,None,...,None,None,None,None,None,None,None,None,None,None
21,MikeyJ,clothing,brand,fundraiser,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
22,Alice,in,Wonderland,in,G,Minor,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
23,Mountain,brew:,A,quest,for,alcohol,sustainability,None,None,None,...,None,None,None,None,None,None,None,None,None,None
24,The,Book,Zoo,-,A,Mini-Comic,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
25,Matt,Cavenaugh,&,Jenny,Powers,make,their,1st,album!,,...,None,None,None,None,None,None,None,None,None,None
26,Superhero,Teddy,Bear,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
27,Permaculture,Skills,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
28,Rebel,Army,Origins:,The,Heroic,Story,Of,Major,Gripes,None,...,None,None,None,None,None,None,None,None,None,None
29,My,Moon,-,Animated,Short,Film,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378631,MONSTROCARDS-,A,Creative,Drawing,Game,of,Horrific,Hilarity,None,None,...,None,None,None,None,None,None,None,None,None,None
378632,"""Loreto""",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378633,STATE,OF,G,-,Men's,Blazer,Jacket,&,Women's,Cardigan,...,None,None,None,None,None,None,None,None,None,None
378634,Transcaucasia,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378635,You're,Not,"Cis,",You,Just,Think,You,Are:,My,Enby,...,None,None,None,None,None,None,None,None,None,None
378636,Little,Saturday's,Debut,Album,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378637,Ways,to,Look,at,the,Moon,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378638,Terminal,Uniqueness,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378639,Superette,Tea,-,Boldly,Caffeinated,Loose,Leaf,Tea,None,None,...,None,None,None,None,None,None,None,None,None,None
378640,Ciridian,Helix,(Canceled),None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378641,Here,is,the,oasis,for,the,youngest,in,the,world.,...,None,None,None,None,None,None,None,None,None,None
378642,ÉPOUVANTAILS,:,28mm,Figurines,de,jeux,pour,KINGS,OF,WAR,...,None,None,None,None,None,None,None,None,None,None
378643,Google,Glass,Shield,(Canceled),None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378644,The,Manual,Bar,Blade,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378645,The,Chronicles,of,Erinoth,-,A,Graphic,Novel,None,None,...,None,None,None,None,None,None,None,None,None,None
378646,The,Dog,Coffee,Book,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378647,The,Cease,is,Increase,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378648,Cards,and,Chit,Network,Season,2!,(Canceled),None,None,None,...,None,None,None,None,None,None,None,None,None,None
378649,Colorado,International,Activism,Film,Festival,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378650,Date,Seat,-,Boston,iOS,App,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378651,AT,THE,BEACH,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378652,Beach,Wrestling,Documentary,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378653,Islanda,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378654,Homemade,fresh,dog,"food,",Cleveland,OH,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378655,Angela's,Poetry,(Canceled),None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378656,ChknTruk,Nationwide,Charity,Drive,2014,(Canceled),None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378657,The,Tribe,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378658,Walls,of,Remedy-,New,lesbian,Romantic,Comedy,feature,unlike,any,...,None,None,None,None,None,None,None,None,None,None
378659,BioDefense,Education,Kit,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
378660,Nou,Renmen,Ayiti!,,We,Love,Haiti!,None,None,None,...,None,None,None,None,None,None,None,None,None,None

22. .str.split(' ',expand=True, n=10) - potnie po spacji i podzieli na kolumny to na 10 kolumn po każdej spacji

In [0]:
seria.str.split(' ',expand=True, n=10)

,0,1,2,3,4,5,6,7,8,9,10
0,The,Songs,of,Adelaide,&,Abullah,None,None,None,None,None
1,Greeting,From,Earth:,ZGAC,Arts,Capsule,For,ET,None,None,None
2,Where,is,Hank?,None,None,None,None,None,None,None,None
3,ToshiCapital,Rekordz,Needs,Help,to,Complete,Album,None,None,None,None
4,Community,Film,Project:,The,Art,of,Neighborhood,Filmmaking,None,None,None
5,Monarch,Espresso,Bar,None,None,None,None,None,None,None,None
6,Support,Solar,Roasted,Coffee,&,Green,Energy!,,SolarCoffee.co,None,None
7,Chaser,Strips.,Our,Strips,make,Shots,their,B*tch!,None,None,None
8,SPIN,-,Premium,Retractable,In-Ear,Headphones,with,Mic,None,None,None
9,STUDIO,IN,THE,SKY,-,A,Documentary,Feature,Film,(Canceled),None
10,Of,Jesus,and,Madmen,None,None,None,None,None,None,None
11,Lisa,Lim,New,CD!,None,None,None,None,None,None,None
12,The,Cottage,Market,None,None,None,None,None,None,None,None
13,G-Spot,Place,for,Gamers,to,connect,with,eachother,&,go,pro!
14,Tombstone:,Old,West,tabletop,game,and,miniatures,in,32mm.,None,None
15,Survival,Rings,None,None,None,None,None,None,None,None,None
16,The,Beard,None,None,None,None,None,None,None,None,None
17,Notes,From,London:,Above,&,Below,None,None,None,None,None
18,Mike,Corey's,Darkness,&,Light,Album,None,None,None,None,None
19,Boco,Tea,None,None,None,None,None,None,None,None,None
20,CMUK.,Shoes:,Take,on,Life,Feet,First.,None,None,None,None
21,MikeyJ,clothing,brand,fundraiser,None,None,None,None,None,None,None
22,Alice,in,Wonderland,in,G,Minor,None,None,None,None,None
23,Mountain,brew:,A,quest,for,alcohol,sustainability,None,None,None,None
24,The,Book,Zoo,-,A,Mini-Comic,None,None,None,None,None
25,Matt,Cavenaugh,&,Jenny,Powers,make,their,1st,album!,,None
26,Superhero,Teddy,Bear,None,None,None,None,None,None,None,None
27,Permaculture,Skills,None,None,None,None,None,None,None,None,None
28,Rebel,Army,Origins:,The,Heroic,Story,Of,Major,Gripes,None,None
29,My,Moon,-,Animated,Short,Film,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...
378631,MONSTROCARDS-,A,Creative,Drawing,Game,of,Horrific,Hilarity,None,None,None
378632,"""Loreto""",None,None,None,None,None,None,None,None,None,None
378633,STATE,OF,G,-,Men's,Blazer,Jacket,&,Women's,Cardigan,None
378634,Transcaucasia,None,None,None,None,None,None,None,None,None,None
378635,You're,Not,"Cis,",You,Just,Think,You,Are:,My,Enby,Epiphany
378636,Little,Saturday's,Debut,Album,None,None,None,None,None,None,None
378637,Ways,to,Look,at,the,Moon,None,None,None,None,None
378638,Terminal,Uniqueness,None,None,None,None,None,None,None,None,None
378639,Superette,Tea,-,Boldly,Caffeinated,Loose,Leaf,Tea,None,None,None
378640,Ciridian,Helix,(Canceled),None,None,None,None,None,None,None,None
378641,Here,is,the,oasis,for,the,youngest,in,the,world.,None
378642,ÉPOUVANTAILS,:,28mm,Figurines,de,jeux,pour,KINGS,OF,WAR,None
378643,Google,Glass,Shield,(Canceled),None,None,None,None,None,None,None
378644,The,Manual,Bar,Blade,None,None,None,None,None,None,None
378645,The,Chronicles,of,Erinoth,-,A,Graphic,Novel,None,None,None
378646,The,Dog,Coffee,Book,None,None,None,None,None,None,None
378647,The,Cease,is,Increase,None,None,None,None,None,None,None
378648,Cards,and,Chit,Network,Season,2!,(Canceled),None,None,None,None
378649,Colorado,International,Activism,Film,Festival,None,None,None,None,None,None
378650,Date,Seat,-,Boston,iOS,App,None,None,None,None,None
378651,AT,THE,BEACH,None,None,None,None,None,None,None,None
378652,Beach,Wrestling,Documentary,None,None,None,None,None,None,None,None
378653,Islanda,None,None,None,None,None,None,None,None,None,None
378654,Homemade,fresh,dog,"food,",Cleveland,OH,None,None,None,None,None
378655,Angela's,Poetry,(Canceled),None,None,None,None,None,None,None,None
378656,ChknTruk,Nationwide,Charity,Drive,2014,(Canceled),None,None,None,None,None
378657,The,Tribe,None,None,None,None,None,None,None,None,None
378658,Walls,of,Remedy-,New,lesbian,Romantic,Comedy,feature,unlike,any,other!!
378659,BioDefense,Education,Kit,None,None,None,None,None,None,None,None
378660,Nou,Renmen,Ayiti!,,We,Love,Haiti!,None,None,None,None

## 3.2 DataFrame

### 3.2.2 Atrybuty

1. .size - rozmiar

In [0]:
df1.size

5622900

2. .index - budowa indexu

In [0]:
df1.index

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            378651, 378652, 378653, 378654, 378655, 378656, 378657, 378658,
            378659, 378660],
           dtype='int64', length=374860)

3. .values - jakie wartości

In [0]:
df1.values

array([[1000002330, 'The Songs of Adelaide & Abullah', 'Poetry', ...,
        0.0, 0.0, 1533.95],
       [1000003930, 'Greeting From Earth: ZGAC Arts Capsule For ET',
        'Narrative Film', ..., 100.0, 2421.0, 30000.0],
       [1000004038, 'Where is Hank?', 'Narrative Film', ..., 220.0,
        220.0, 45000.0],
       ...,
       [999986353,
        'Walls of Remedy- New lesbian Romantic Comedy feature unlike any other!!',
        'Narrative Film', ..., 20.0, 20.0, 15000.0],
       [999987933, 'BioDefense Education Kit', 'Technology', ..., 200.0,
        200.0, 15000.0],
       [999988282, 'Nou Renmen Ayiti!  We Love Haiti!',
        'Performance Art', ..., 524.0, 524.0, 2000.0]], dtype=object)

4. .dtypes - jakie typ warotści

In [0]:
df1.dtypes

ID                    int64
name                 object
category             object
main_category        object
currency             object
deadline             object
goal                float64
launched             object
pledged             float64
state                object
backers               int64
country              object
usd pledged         float64
usd_pledged_real    float64
usd_goal_real       float64
dtype: object

5. .shape - kształt, ile jest wierszy i ile jest kolumn

In [0]:
df1.shape

(374860, 15)

6. .axes

In [0]:
df1.axes

[Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                  8,      9,
             ...
             378651, 378652, 378653, 378654, 378655, 378656, 378657, 378658,
             378659, 378660],
            dtype='int64', length=374860),
 Index(['ID', 'name', 'category', 'main_category', 'currency', 'deadline',
        'goal', 'launched', 'pledged', 'state', 'backers', 'country',
        'usd pledged', 'usd_pledged_real', 'usd_goal_real'],
       dtype='object')]

7. columns - zwraca nazwy kolumny

In [0]:
df1.columns

Index(['ID', 'name', 'category', 'main_category', 'currency', 'deadline',
       'goal', 'launched', 'pledged', 'state', 'backers', 'country',
       'usd pledged', 'usd_pledged_real', 'usd_goal_real'],
      dtype='object')

### 3.2.2 Metody

1. .sum() - uwaga, strasznie procesożerne na tym zbiorze danych!!!

In [0]:
df1.sum()

2. .min() - uwaga, strasznie procesożerne na tym zbiorze danych!!!

In [0]:
df1.min()

3. .max() - uwaga, strasznie procesożerne na tym zbiorze danych!!!

In [0]:
df1.max()

4. .count()

In [0]:
df1.count()

ID                  374860
name                374860
category            374860
main_category       374860
currency            374860
deadline            374860
goal                374860
launched            374860
pledged             374860
state               374860
backers             374860
country             374860
usd pledged         374860
usd_pledged_real    374860
usd_goal_real       374860
dtype: int64

5. .product - wymnarza wszystko przez siebie i zwraca wynik

In [0]:
df1.product

<bound method DataFrame.prod of                 ID                                               name  \
0       1000002330                    The Songs of Adelaide & Abullah
1       1000003930      Greeting From Earth: ZGAC Arts Capsule For ET
2       1000004038                                     Where is Hank?
3       1000007540  ToshiCapital Rekordz Needs Help to Complete Album
4       1000011046  Community Film Project: The Art of Neighborhoo...
5       1000014025                               Monarch Espresso Bar
6       1000023410  Support Solar Roasted Coffee & Green Energy!  ...
7       1000030581  Chaser Strips. Our Strips make Shots their B*tch!
8       1000034518  SPIN - Premium Retractable In-Ear Headphones w...
9        100004195  STUDIO IN THE SKY - A Documentary Feature Film...
10       100004721                                Of Jesus and Madmen
11       100005484                                   Lisa Lim New CD!
12      1000055792                                 The Cottage Market
13      1000056157  G-Spot Place for Gamers to connect with eachot...
14      1000057089  Tombstone: Old West tabletop game and miniatur...
15      1000064368                                     Survival Rings
16      1000064918                                          The Beard
17      1000068480                   Notes From London: Above & Below
18      1000070642                Mike Corey's Darkness & Light Album
19      1000071625                                           Boco Tea
20      1000072011              CMUK. Shoes: Take on Life Feet First.
21      1000081649                   MikeyJ clothing brand fundraiser
22      1000082254                     Alice in Wonderland in G Minor
23      1000087442  Mountain brew: A quest for alcohol sustainability
24      1000091520                        The Book Zoo - A Mini-Comic
25      1000102741  Matt Cavenaugh & Jenny Powers make their 1st a...
26      1000103948                               Superhero Teddy Bear
27      1000104688                                Permaculture Skills
28      1000104953  Rebel Army Origins: The Heroic Story Of Major ...
29       100011318                      My Moon - Animated Short Film
...            ...                                                ...
378631   999832803  MONSTROCARDS- A Creative Drawing Game of Horri...
378632    99984851                                           "Loreto"
378633   999865831  STATE OF G - Men's Blazer Jacket & Women's Car...
378634   999867839                                      Transcaucasia
378635    99987261  You're Not Cis, You Just Think You Are: My Enb...
378636   999877902                      Little Saturday's Debut Album
378637   999878813                           Ways to Look at the Moon
378638   999880710                                Terminal Uniqueness
378639   999884445  Superette Tea - Boldly Caffeinated Loose Leaf Tea
378640   999893629                          Ciridian Helix (Canceled)
378641    99991751   Here is the oasis for the youngest in the world.
378642   999929142  ÉPOUVANTAILS : 28mm Figurines de jeux pour KIN...
378643   999931480                     Google Glass Shield (Canceled)
378644   999934908                               The Manual Bar Blade
378645   999941823        The Chronicles of Erinoth - A Graphic Novel
378646   999943841                                The Dog Coffee Book
378647   999950812                              The Cease is Increase
378648   999955533        Cards and Chit Network Season 2! (Canceled)
378649   999963618      Colorado International Activism Film Festival
378650    99996661                         Date Seat - Boston iOS App
378651   999969812                                       AT THE BEACH
378652   999971898                        Beach Wrestling Documentary
378653   999972264                                            Islanda
378654   999975836              Homemade fresh dog food, Cleveland OH
378655   999976312                         Angela's Poetry (Canceled)
378656   999976400  ChknTruk Nationwide Charity Drive 2014 (Canceled)
378657   999977640                                          The Tribe
378658   999986353  Walls of Remedy- New lesbian Romantic Comedy f...
378659   999987933                           BioDefense Education Kit
378660   999988282                  Nou Renmen Ayiti!  We Love Haiti!

                category main_category currency    deadline      goal  \
0                 Poetry    Publishing      GBP  2015-10-09    1000.0
1         Narrative Film  Film & Video      USD  2017-11-01   30000.0
2         Narrative Film  Film & Video      USD  2013-02-26   45000.0
3                  Music         Music      USD  2012-04-16    5000.0
4           Film & Video  Film & Video      USD  2015-08-29   19500.0
5            Restaurants          Food      USD  2016-04-01   50000.0
6                   Food          Food      USD  2014-12-21    1000.0
7                 Drinks          Food      USD  2016-03-17   25000.0
8         Product Design        Design      USD  2014-05-29  125000.0
9            Documentary  Film & Video      USD  2014-08-10   65000.0
10            Nonfiction    Publishing      CAD  2013-10-09    2500.0
11            Indie Rock         Music      USD  2013-04-08   12500.0
12                Crafts        Crafts      USD  2014-10-02    5000.0
13                 Games         Games      USD  2016-03-25  200000.0
14        Tabletop Games         Games      GBP  2017-05-03    5000.0
15                Design        Design      USD  2015-02-28    2500.0
16           Comic Books        Comics      USD  2014-11-08    1500.0
17             Art Books    Publishing      USD  2015-05-10    3000.0
18                 Music         Music      USD  2012-08-17     250.0
19                  Food          Food      USD  2012-06-02    5000.0
20               Fashion       Fashion      USD  2013-12-30   20000.0
21         Childrenswear       Fashion      AUD  2017-09-07    2500.0
22               Theater       Theater      USD  2014-06-15    3500.0
23                Drinks          Food      NOK  2015-02-25     500.0
24                Comics        Comics      USD  2014-11-12     175.0
25                 Music         Music      USD  2011-01-06   10000.0
26                   DIY        Crafts      GBP  2016-01-05   12000.0
27             Webseries  Film & Video      CAD  2014-12-14   17757.0
28                Comics        Comics      GBP  2016-01-28     100.0
29             Animation  Film & Video      USD  2017-05-03   50000.0
...                  ...           ...      ...         ...       ...
378631     Playing Cards         Games      USD  2014-10-03   10000.0
378632            Comedy  Film & Video      USD  2014-06-05   12000.0
378633           Apparel       Fashion      USD  2014-12-13   25000.0
378634       Photography   Photography      USD  2011-01-08    4000.0
378635        Nonfiction    Publishing      USD  2015-09-24     800.0
378636    Country & Folk         Music      CAD  2014-12-17    5000.0
378637            Shorts  Film & Video      USD  2017-10-13   10000.0
378638        Nonfiction    Publishing      USD  2014-08-15    5000.0
378639            Drinks          Food      USD  2015-12-03    5000.0
378640           Fiction    Publishing      USD  2014-09-11    1000.0
378641    Product Design        Design      CHF  2015-09-04   80000.0
378642    Tabletop Games         Games      EUR  2017-10-31    1000.0
378643       3D Printing    Technology      USD  2014-05-26    6500.0
378644    Product Design        Design      USD  2015-12-15    3500.0
378645            Comics        Comics      GBP  2013-10-10   16000.0
378646  Children's Books    Publishing      USD  2013-11-30     950.0
378647        Nonfiction    Publishing      USD  2012-09-14    4999.0
378648    Tabletop Games         Games      USD  2016-02-23     500.0
378649    Narrative Film  Film & Video      USD  2017-04-09     500.0
378650              Apps    Technology      USD  2016-09-05    6000.0
378651   Classical Music         Music      CAD  2014-03-22    5000.0
378652       Documentary  Film & Video      NOK  2015-04-28   20000.0
378653       Documentary  Film & Video      USD  2012-03-16    1700.0
378654       Small Batch          Food      USD  2017-04-19    6500.0
378655            Poetry    Publishing      CAD  2014-09-20    5500.0
378656       Documentary  Film & Video      USD  2014-10-17   50000.0
378657    Narrative Film  Film & Video      USD  2011-07-19    1500.0
378658    Narrative Film  Film & Video      USD  2010-08-16   15000.0
378659        Technology    Technology      USD  2016-02-13   15000.0
378660   Performance Art           Art      USD  2011-08-16    2000.0

                   launched   pledged       state  backers country  \
0       2015-08-11 12:12:28      0.00      failed        0      GB
1       2017-09-02 04:43:57   2421.00      failed       15      US
2       2013-01-12 00:20:50    220.00      failed        3      US
3       2012-03-17 03:24:11      1.00      failed        1      US
4       2015-07-04 08:35:03   1283.00    canceled       14      US
5       2016-02-26 13:38:27  52375.00  successful      224      US
6       2014-12-01 18:30:44   1205.00  successful       16      US
7       2016-02-01 20:05:12    453.00      failed       40      US
8       2014-04-24 18:14:43   8233.00    canceled       58      US
9       2014-07-11 21:55:48   6240.57    canceled       43      US
10      2013-09-09 18:19:37      0.00      failed        0      CA
11      2013-03-09 06:42:58  12700.00  successful      100      US
12      2014-09-02 17:11:50      0.00      failed        0      US
13      2016-02-09 23:01:12      0.00      failed        0      US
14      2017-04-05 19:44:18  94175.00  successful      761      GB
15      2015-01-29 02:10:53    664.00      failed       11      US
16      2014-10-09 22:27:52    395.00      failed       16      US
17      2015-04-10 21:20:54    789.00      failed       20      US
18      2012-08-02 14:11:32    250.00  successful        7      US
19      2012-05-03 17:24:32   1781.00      failed       40      US
20      2013-11-25 07:06:11  34268.00  successful      624      US
21      2017-08-08 01:20:20      1.00      failed        1      AU
22      2014-05-16 10:10:38    650.00      failed       12      US
23      2015-01-26 19:17:33     48.00      failed        3      NO
24      2014-10-23 17:15:50    701.66  successful       66      US
25      2010-12-07 23:16:50  15827.00  successful      147      US
26      2015-12-06 20:09:06      0.00      failed        0      GB
27      2014-11-14 18:02:00  48905.00  successful      571      CA
28      2015-12-29 16:59:29    112.38  successful       27      GB
29      2017-04-03 17:11:33  57577.31  successful      840      US
...                     ...       ...         ...      ...     ...
378631  2014-09-03 19:53:50  13861.50  successful      413      US
378632  2014-05-06 23:50:34      0.00      failed        0      US
378633  2014-11-13 17:16:17  11643.00      failed       97      US
378634  2010-11-08 02:43:59   3531.00      failed       37      US
378635  2015-08-25 22:37:14     70.00      failed        5      US
378636  2014-11-17 17:50:12   5435.00  successful       78      CA
378637  2017-08-29 06:57:28  10245.00  successful      123      US
378638  2014-07-15 02:10:39     18.00      failed        5      US
378639  2015-11-03 13:04:14   5579.00  successful      103      US
378640  2014-08-08 21:49:31    100.00    canceled        2      US
378641  2015-07-06 18:00:47      0.00      failed        0      CH
378642  2017-10-04 11:26:44   1246.00  successful       35      FR
378643  2014-05-05 20:22:45      0.00    canceled        0      US
378644  2015-11-23 07:33:14   6169.00  successful      120      US
378645  2013-09-10 22:45:26   2738.00      failed       38      GB
378646  2013-10-18 21:35:04   1732.02  successful       31      US
378647  2012-08-15 17:11:00    980.00      failed       16      US
378648  2016-01-24 16:03:27    121.00    canceled        5      US
378649  2017-02-08 02:28:44    135.00      failed        6      US
378650  2016-07-29 15:36:29      0.00      failed        0      US
378651  2014-02-20 01:00:16   5501.00  successful       78      CA
378652  2015-03-29 21:30:33  21500.00  successful       36      NO
378653  2012-02-15 04:31:10     25.00      failed        1      US
378654  2017-03-20 22:08:22    154.00      failed        4      US
378655  2014-08-06 03:46:07      0.00    canceled        0      CA
378656  2014-09-17 02:35:30     25.00    canceled        1      US
378657  2011-06-22 03:35:14    155.00      failed        5      US
378658  2010-07-01 19:40:30     20.00      failed        1      US
378659  2016-01-13 18:13:53    200.00      failed        6      US
378660  2011-07-19 09:07:47    524.00      failed       17      US

        usd pledged  usd_pledged_real  usd_goal_real
0              0.00              0.00        1533.95
1            100.00           2421.00       30000.00
2            220.00            220.00       45000.00
3              1.00              1.00        5000.00
4           1283.00           1283.00       19500.00
5          52375.00          52375.00       50000.00
6           1205.00           1205.00        1000.00
7            453.00            453.00       25000.00
8           8233.00           8233.00      125000.00
9           6240.57           6240.57       65000.00
10             0.00              0.00        2406.39
11         12700.00          12700.00       12500.00
12             0.00              0.00        5000.00
13             0.00              0.00      200000.00
14         57763.78         121857.33        6469.73
15           664.00            664.00        2500.00
16           395.00            395.00        1500.00
17           789.00            789.00        3000.00
18           250.00            250.00         250.00
19          1781.00           1781.00        5000.00
20         34268.00          34268.00       20000.00
21             0.00              0.81        2026.10
22           650.00            650.00        3500.00
23             6.18              6.29          65.55
24           701.66            701.66         175.00
25         15827.00          15827.00       10000.00
26             0.00              0.00       17489.65
27         43203.25          42174.03       15313.04
28           167.70            160.60         142.91
29         10120.00          57577.31       50000.00
...             ...               ...            ...
378631     13861.50          13861.50       10000.00
378632         0.00              0.00       12000.00
378633     11643.00          11643.00       25000.00
378634      3531.00           3531.00        4000.00
378635        70.00             70.00         800.00
378636      4814.88           4686.96        4311.83
378637       145.00          10245.00       10000.00
378638        18.00             18.00        5000.00
378639      5579.00           5579.00        5000.00
378640       100.00            100.00        1000.00
378641         0.00              0.00       82207.27
378642        66.72           1452.47        1165.70
378643         0.00              0.00        6500.00
378644      6169.00           6169.00        3500.00
378645      4281.15           4374.99       25566.05
378646      1732.02           1732.02         950.00
378647       980.00            980.00        4999.00
378648       121.00            121.00         500.00
378649        45.00            135.00         500.00
378650         0.00              0.00        6000.00
378651      5019.92           4983.69        4529.81
378652      2698.97           2875.83        2675.19
378653        25.00             25.00        1700.00
378654         0.00            154.00        6500.00
378655         0.00              0.00        4949.60
378656        25.00             25.00       50000.00
378657       155.00            155.00        1500.00
378658        20.00             20.00       15000.00
378659       200.00            200.00       15000.00
378660       524.00            524.00        2000.00

[374860 rows x 15 columns]>

6. .keys()

In [0]:
df1.keys()

Index(['ID', 'name', 'category', 'main_category', 'currency', 'deadline',
       'goal', 'launched', 'pledged', 'state', 'backers', 'country',
       'usd pledged', 'usd_pledged_real', 'usd_goal_real'],
      dtype='object')

7. .get_values()

In [0]:
df1.get_values()

array([[1000002330, 'The Songs of Adelaide & Abullah', 'Poetry', ...,
        0.0, 0.0, 1533.95],
       [1000003930, 'Greeting From Earth: ZGAC Arts Capsule For ET',
        'Narrative Film', ..., 100.0, 2421.0, 30000.0],
       [1000004038, 'Where is Hank?', 'Narrative Film', ..., 220.0,
        220.0, 45000.0],
       ...,
       [999986353,
        'Walls of Remedy- New lesbian Romantic Comedy feature unlike any other!!',
        'Narrative Film', ..., 20.0, 20.0, 15000.0],
       [999987933, 'BioDefense Education Kit', 'Technology', ..., 200.0,
        200.0, 15000.0],
       [999988282, 'Nou Renmen Ayiti!  We Love Haiti!',
        'Performance Art', ..., 524.0, 524.0, 2000.0]], dtype=object)

8. .add() - Można dodawać wartości i inne dataframey - mam nadzieję, że na zajęciach bardziej wyjaśnią

In [0]:
df1.add(df1).head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,2000004660,The Songs of Adelaide & AbullahThe Songs of Ad...,PoetryPoetry,PublishingPublishing,GBPGBP,2015-10-092015-10-09,2000.0,2015-08-11 12:12:282015-08-11 12:12:28,0.0,failedfailed,0,GBGB,0.0,0.0,3067.9
1,2000007860,Greeting From Earth: ZGAC Arts Capsule For ETG...,Narrative FilmNarrative Film,Film & VideoFilm & Video,USDUSD,2017-11-012017-11-01,60000.0,2017-09-02 04:43:572017-09-02 04:43:57,4842.0,failedfailed,30,USUS,200.0,4842.0,60000.0
2,2000008076,Where is Hank?Where is Hank?,Narrative FilmNarrative Film,Film & VideoFilm & Video,USDUSD,2013-02-262013-02-26,90000.0,2013-01-12 00:20:502013-01-12 00:20:50,440.0,failedfailed,6,USUS,440.0,440.0,90000.0
3,2000015080,ToshiCapital Rekordz Needs Help to Complete Al...,MusicMusic,MusicMusic,USDUSD,2012-04-162012-04-16,10000.0,2012-03-17 03:24:112012-03-17 03:24:11,2.0,failedfailed,2,USUS,2.0,2.0,10000.0
4,2000022092,Community Film Project: The Art of Neighborhoo...,Film & VideoFilm & Video,Film & VideoFilm & Video,USDUSD,2015-08-292015-08-29,39000.0,2015-07-04 08:35:032015-07-04 08:35:03,2566.0,canceledcanceled,28,USUS,2566.0,2566.0,39000.0

9. .reindex() - przebudowywanie indexu, można też zastąpić tą metodą NULLe parametrem **fill_value**

In [0]:
df1.reindex().head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00

10. .get_dtype_counts() - zlicza ilość kolumn danego typu

In [0]:
df1.get_dtype_counts()

float64    5
int64      2
object     8
dtype: int64

11. .info() - ile wartości w kolumnach i jakego typu

In [0]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 374860 entries, 0 to 378660
Data columns (total 15 columns):
ID                  374860 non-null int64
name                374860 non-null object
category            374860 non-null object
main_category       374860 non-null object
currency            374860 non-null object
deadline            374860 non-null object
goal                374860 non-null float64
launched            374860 non-null object
pledged             374860 non-null float64
state               374860 non-null object
backers             374860 non-null int64
country             374860 non-null object
usd pledged         374860 non-null float64
usd_pledged_real    374860 non-null float64
usd_goal_real       374860 non-null float64
dtypes: float64(5), int64(2), object(8)
memory usage: 45.8+ MB

12. .sample() - losowanie kilku wartości

In [0]:
df1.sample()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
17609,1089428483,Juiceros - An Organic Cold-Pressed juicery,Food,Food,USD,2013-10-14,35000.0,2013-08-30 10:17:54,11320.0,failed,67,US,11320.0,11320.0,35000.0

13. .nlargest() - największe wartości dla (1,columns='nazwa kolumny')

In [0]:
df1.nlargest(1,columns='ID')

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
225212,2147476221,DrinkTanks Offers the World's Largest Growler ...,Drinks,Food,USD,2015-04-10,75000.0,2015-03-02 16:14:38,304142.0,successful,2076,US,304142.0,304142.0,75000.0

14. .rename - zmiana nazwy kolumny .rename({'SupplierID':'CustomerID'},axis='columns',inplace=True)

In [0]:
df1.rename({'name':'Nazwa'},axis='columns').head()

,ID,Nazwa,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00

15. .set_index - ustawiamy index

In [0]:
df1.set_index('name').head()

,ID,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
name,,,,,,,,,,,,,,
The Songs of Adelaide & Abullah,1000002330,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
Greeting From Earth: ZGAC Arts Capsule For ET,1000003930,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
Where is Hank?,1000004038,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
ToshiCapital Rekordz Needs Help to Complete Album,1000007540,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
Community Film Project: The Art of Neighborhood Filmmaking,1000011046,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00

### 3.2.3 Grupowanie dancyh oraz agregacje

1. .groupby([kolumny]) - pewnego rodzaju filtra do grupowania, zwraca obiekt, niestety zwraca też oryginalne położenie kolumn!

In [0]:
name_category=df1.groupby(['main_category','category'])
name_category.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.00,failed,0,GB,0.00,0.00,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.00,failed,15,US,100.00,2421.00,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.00,failed,3,US,220.00,220.00,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.00,failed,1,US,1.00,1.00,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.00,canceled,14,US,1283.00,1283.00,19500.00
5,1000014025,Monarch Espresso Bar,Restaurants,Food,USD,2016-04-01,50000.0,2016-02-26 13:38:27,52375.00,successful,224,US,52375.00,52375.00,50000.00
6,1000023410,Support Solar Roasted Coffee & Green Energy! ...,Food,Food,USD,2014-12-21,1000.0,2014-12-01 18:30:44,1205.00,successful,16,US,1205.00,1205.00,1000.00
7,1000030581,Chaser Strips. Our Strips make Shots their B*tch!,Drinks,Food,USD,2016-03-17,25000.0,2016-02-01 20:05:12,453.00,failed,40,US,453.00,453.00,25000.00
8,1000034518,SPIN - Premium Retractable In-Ear Headphones w...,Product Design,Design,USD,2014-05-29,125000.0,2014-04-24 18:14:43,8233.00,canceled,58,US,8233.00,8233.00,125000.00
9,100004195,STUDIO IN THE SKY - A Documentary Feature Film...,Documentary,Film & Video,USD,2014-08-10,65000.0,2014-07-11 21:55:48,6240.57,canceled,43,US,6240.57,6240.57,65000.00
10,100004721,Of Jesus and Madmen,Nonfiction,Publishing,CAD,2013-10-09,2500.0,2013-09-09 18:19:37,0.00,failed,0,CA,0.00,0.00,2406.39
11,100005484,Lisa Lim New CD!,Indie Rock,Music,USD,2013-04-08,12500.0,2013-03-09 06:42:58,12700.00,successful,100,US,12700.00,12700.00,12500.00
12,1000055792,The Cottage Market,Crafts,Crafts,USD,2014-10-02,5000.0,2014-09-02 17:11:50,0.00,failed,0,US,0.00,0.00,5000.00
13,1000056157,G-Spot Place for Gamers to connect with eachot...,Games,Games,USD,2016-03-25,200000.0,2016-02-09 23:01:12,0.00,failed,0,US,0.00,0.00,200000.00
14,1000057089,Tombstone: Old West tabletop game and miniatur...,Tabletop Games,Games,GBP,2017-05-03,5000.0,2017-04-05 19:44:18,94175.00,successful,761,GB,57763.78,121857.33,6469.73
15,1000064368,Survival Rings,Design,Design,USD,2015-02-28,2500.0,2015-01-29 02:10:53,664.00,failed,11,US,664.00,664.00,2500.00
16,1000064918,The Beard,Comic Books,Comics,USD,2014-11-08,1500.0,2014-10-09 22:27:52,395.00,failed,16,US,395.00,395.00,1500.00
17,1000068480,Notes From London: Above & Below,Art Books,Publishing,USD,2015-05-10,3000.0,2015-04-10 21:20:54,789.00,failed,20,US,789.00,789.00,3000.00
18,1000070642,Mike Corey's Darkness & Light Album,Music,Music,USD,2012-08-17,250.0,2012-08-02 14:11:32,250.00,successful,7,US,250.00,250.00,250.00
19,1000071625,Boco Tea,Food,Food,USD,2012-06-02,5000.0,2012-05-03 17:24:32,1781.00,failed,40,US,1781.00,1781.00,5000.00
20,1000072011,CMUK. Shoes: Take on Life Feet First.,Fashion,Fashion,USD,2013-12-30,20000.0,2013-11-25 07:06:11,34268.00,successful,624,US,34268.00,34268.00,20000.00
21,1000081649,MikeyJ clothing brand fundraiser,Childrenswear,Fashion,AUD,2017-09-07,2500.0,2017-08-08 01:20:20,1.00,failed,1,AU,0.00,0.81,2026.10
22,1000082254,Alice in Wonderland in G Minor,Theater,Theater,USD,2014-06-15,3500.0,2014-05-16 10:10:38,650.00,failed,12,US,650.00,650.00,3500.00
23,1000087442,Mountain brew: A quest for alcohol sustainability,Drinks,Food,NOK,2015-02-25,500.0,2015-01-26 19:17:33,48.00,failed,3,NO,6.18,6.29,65.55
24,1000091520,The Book Zoo - A Mini-Comic,Comics,Comics,USD,2014-11-12,175.0,2014-10-23 17:15:50,701.66,successful,66,US,701.66,701.66,175.00
25,1000102741,Matt Cavenaugh & Jenny Powers make their 1st a...,Music,Music,USD,2011-01-06,10000.0,2010-12-07 23:16:50,15827.00,successful,147,US,15827.00,15827.00,10000.00
26,1000103948,Superhero Teddy Bear,DIY,Crafts,GBP,2016-01-05,12000.0,2015-12-06 20:09:06,0.00,failed,0,GB,0.00,0.00,17489.65
27,1000104688,Permaculture Skills,Webseries,Film & Video,CAD,2014-12-14,17757.0,2014-11-14 18:02:00,48905.00,successful,571,CA,43203.25,42174.03,15313.04
28,1000104953,Rebel Army Origins: The Heroic Story Of Major ...,Comics,Comics,GBP,2016-01-28,100.0,2015-12-29 16:59:29,112.38,successful,27,GB,167.70,160.60,142.91
29,100011318,My Moon - Animated Short Film,Animation,Film & Video,USD,2017-05-03,50000.0,2017-04-03 17:11:33,57577.31,successful,840,US,10120.00,57577.31,50000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21025,1106609654,Arctic Crafts (Canceled),Quilts,Crafts,USD,2014-08-08,45000.0,2014-07-09 18:29:50,0.00,canceled,0,US,0.00,0.00,45000.00
21581,1109451901,Exclusive Fabric Cutting Dies by LoveBug Studios,Quilts,Crafts,USD,2017-10-25,17000.0,2017-09-25 14:58:54,29537.00,successful,227,US,305.00,29537.00,17000.00
22014,1111529080,Ento Wreaths (Holiday themed wreaths with real...,Taxidermy,Crafts,USD,2017-01-18,500.0,2016-12-19 09:55:12,502.00,successful,14,US,10.00,502.00,500.00
22807,1115761193,Destroy All Presets: ? re-mixable chiptune album!,Chiptune,Music,USD,2014-02-13,6500.0,2014-01-13 16:06:09,11387.71,successful,352,US,11387.71,11387.71,6500.00
22912,1116274846,"Residencia en Guanajuato para ensayo de ""La Ca...",Residencies,Dance,MXN,2017-10-12,10000.0,2017-09-12 04:04:43,650.00,failed,4,MX,0.00,34.29,527.51
23953,1121594377,My boyfriend can't dress himself.,Comedy,Publishing,EUR,2017-12-06,30000.0,2017-11-06 19:51:47,0.00,failed,0,IT,0.00,0.00,35226.15
24181,1122655302,"Professor shyguy - Chiptune Pop Album, Video, ...",Chiptune,Music,USD,2013-05-24,3500.0,2013-05-01 06:26:06,5013.13,successful,174,US,5013.13,5013.13,3500.00
25670,1130472848,Kickstarter Gold: BIBLIOTHECA,Typography,Design,USD,2017-07-22,37000.0,2017-06-21 21:11:39,109452.00,successful,631,US,12670.00,109452.00,37000.00
27444,1139432631,Loving New York - Der innovativste Reiseführer...,Letterpress,Publishing,EUR,2017-05-13,20000.0,2017-04-13 14:02:37,20953.00,successful,407,DE,1407.95,23423.47,22358.11
30520,1155117741,Bliss Books & Bindery: A Community Bookstore!,Literary Spaces,Publishing,USD,2017-07-13,15000.0,2017-06-13 17:00:24,2436.00,failed,45,US,212.00,2436.00,15000.00
31826,1161730817,¡Ayúdame a traducir Estatua Busca Plaza Tranqu...,Comedy,Publishing,EUR,2017-12-26,2600.0,2017-10-27 12:51:38,2637.00,successful,69,ES,679.93,3162.55,3118.18
34691,1175911553,One Year of Polymer Letterpress,Letterpress,Crafts,USD,2014-02-08,600.0,2014-01-24 03:49:24,1038.00,successful,50,US,1038.00,1038.00,600.00
37001,1187694799,Cascade Youth Dance: Commonwealth,Residencies,Dance,GBP,2014-06-30,1000.0,2014-05-26 20:09:32,1170.00,successful,9,GB,1969.26,2005.79,1714.35
39991,1203401757,Plastic Identities,Residencies,Dance,USD,2017-07-20,6500.0,2017-06-20 23:07:41,7106.99,successful,85,US,543.00,7106.99,6500.00
40859,1208011665,Hollow Earth. Perth's 1st Oddity store (Canceled),Taxidermy,Crafts,AUD,2016-01-20,10000.0,2015-12-18 03:19:58,75.00,canceled,3,AU,54.07,52.71,7027.41
49862,1254031717,Peter & Co. SF Presents at The Garage,Residencies,Dance,USD,2014-08-02,4500.0,2014-07-03 01:05:55,805.00,failed,24,US,805.00,805.00,4500.00
50851,1258935393,Back in Time Symphonic Collection - C64 Sympho...,Chiptune,Music,GBP,2015-12-02,30000.0,2015-10-21 08:33:49,37501.00,successful,606,GB,58029.26,56774.97,45418.76
54138,127554343,Mariachi Entertainment System's 2nd Album,Chiptune,Music,USD,2016-07-31,8000.0,2016-06-25 18:44:01,8744.00,successful,197,US,3682.00,8744.00,8000.00
58508,1297521920,Grow with the Independent Publishing Resource ...,Literary Spaces,Publishing,USD,2018-01-05,20000.0,2017-11-27 18:07:05,15212.00,live,220,US,1281.00,15212.00,20000.00
63571,1323294718,Turn my house into a ball pit party.,Residencies,Dance,CAD,2014-11-27,1000.0,2014-10-28 07:30:04,1.00,failed,1,CA,0.89,0.88,877.42
66444,1337954163,Healthy Italian Vegetarian Food,Letterpress,Publishing,EUR,2018-01-25,2000.0,2017-11-26 11:24:49,26.00,live,2,DE,0.00,31.56,2427.39
68312,1347766761,Best of Commodore Amiga Demoscene Music (Cance...,Chiptune,Music,EUR,2015-07-18,500.0,2015-06-18 18:14:34,28.00,canceled,7,DE,31.51,30.63,546.95
69684,1354632640,Ich und mein Süchtiges Ich - Autobiografisches...,Letterpress,Publishing,EUR,2017-12-30,500.0,2017-11-30 18:22:53,5.00,failed,1,DE,0.00,6.02,602.25
72753,1370425060,Virginia the Wolf needs a new studio,Taxidermy,Crafts,GBP,2015-06-10,10000.0,2015-05-11 21:39:21,1796.00,failed,24,GB,2774.86,2781.39,15486.59
76565,1389650346,Help Me Make My Album!!,Comedy,Music,USD,2017-01-30,3000.0,2017-01-14 21:02:58,388.00,failed,26,US,91.00,388.00,3000.00
80656,1410073362,The Berlin Sixty-Six Deck,Letterpress,Publishing,USD,2017-11-02,4000.0,2017-10-05 00:03:14,7345.00,successful,83,US,3750.00,7345.00,4000.00
87235,144343605,"Boom Boom Baby, a bilingual variety type enter...",Comedy,Music,USD,2017-07-01,90000.0,2017-05-02 20:23:13,351.00,failed,8,US,26.00,351.00,90000.00
88546,1450117214,CaptainsCuriosities Taxidermy animal art,Taxidermy,Crafts,GBP,2015-03-08,300.0,2015-02-06 08:50:42,1.00,failed,1,GB,1.52,1.48,443.43
93812,1476874265,Home based exercise program for men with prost...,Literary Spaces,Publishing,AUD,2017-11-15,22500.0,2017-10-17 08:31:26,905.00,failed,7,AU,64.59,682.86,16977.29
115685,1587351872,50/50 Bookstore: A Pay What You Can Bookstore ...,Literary Spaces,Publishing,USD,2018-01-11,9000.0,2017-12-12 17:17:16,4874.00,live,39,US,295.00,4874.00,9000.00

2. .get_group((val1,val2)) - wydobywanie specyficznej wartości z grupy, uwaga trzeba zwrócić uwagę na to jak zostało coś zgrupowane

In [0]:
name_category.get_group(('Food','Food'))

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
6,1000023410,Support Solar Roasted Coffee & Green Energy! ...,Food,Food,USD,2014-12-21,1000.0,2014-12-01 18:30:44,1205.00,successful,16,US,1205.00,1205.00,1000.00
19,1000071625,Boco Tea,Food,Food,USD,2012-06-02,5000.0,2012-05-03 17:24:32,1781.00,failed,40,US,1781.00,1781.00,5000.00
74,1000282287,Babe Ruth's Family Kitchen - Gourmet Hot Dogs ...,Food,Food,USD,2015-10-13,25000.0,2015-09-08 00:59:36,0.00,canceled,0,US,0.00,0.00,25000.00
113,1000476123,Mama's Meatballs,Food,Food,USD,2014-08-07,100.0,2014-07-08 18:52:26,0.00,failed,0,US,0.00,0.00,100.00
203,1000834930,Strawberry Fields Café and Patisserie,Food,Food,CAD,2017-01-23,50000.0,2016-12-01 21:16:27,0.00,failed,0,CA,0.00,0.00,38112.66
230,100101389,"Uptown Juice Company: Local, cold-pressed good...",Food,Food,USD,2014-04-01,25000.0,2014-02-25 00:15:17,30066.00,successful,161,US,30066.00,30066.00,25000.00
256,1001135664,BrewStick ~ carboy ruler,Food,Food,USD,2014-03-24,22500.0,2014-02-22 22:45:11,50.00,failed,2,US,50.00,50.00,22500.00
293,1001302832,"The Farmer, the Bean and the Holy Roast",Food,Food,USD,2013-02-21,3500.0,2013-01-22 22:58:00,1278.00,failed,29,US,1278.00,1278.00,3500.00
378,1001762923,Spicing it Up at Whipped & Beaten Culinary Works,Food,Food,USD,2013-03-21,2500.0,2013-02-19 16:02:28,3712.00,successful,125,US,3712.00,3712.00,2500.00
403,1001899204,Black Knight Brick Built BBQ Grill,Food,Food,GBP,2014-10-09,15000.0,2014-08-25 19:19:14,0.00,failed,0,GB,0.00,0.00,24051.18
424,1002027893,Flyover Farm,Food,Food,USD,2012-05-07,5500.0,2012-04-16 08:36:41,6510.00,successful,133,US,6510.00,6510.00,5500.00
441,1002117681,"Yemanja Caribbean Restaurant, Bar, and Hostel",Food,Food,USD,2012-09-21,15000.0,2012-08-22 18:29:37,16656.00,successful,160,US,16656.00,16656.00,15000.00
491,1002368838,Starting A Herb Garden,Food,Food,AUD,2014-11-22,4500.0,2014-10-23 01:30:31,0.00,failed,0,AU,0.00,0.00,3835.01
558,1002717273,Bull & Dragon's Pop-Up Restaurant Project,Food,Food,USD,2013-09-07,34000.0,2013-07-29 23:29:10,596.00,failed,14,US,596.00,596.00,34000.00
597,1002884058,Top Chefs Opening Shakewell Bar & Kitchen!,Food,Food,USD,2013-08-22,100000.0,2013-07-23 18:18:09,102937.00,successful,443,US,102937.00,102937.00,100000.00
624,1002985353,Bona Dea Gluten Free Goodness,Food,Food,USD,2012-02-01,8000.0,2011-12-22 18:43:31,8540.00,successful,107,US,8540.00,8540.00,8000.00
679,1003343308,"PowerBark-""Meal on the Run for the Dog on the Go""",Food,Food,USD,2014-06-13,5000.0,2014-05-14 23:03:53,2186.00,failed,25,US,2186.00,2186.00,5000.00
699,1003441266,"Vanilley Bean Treats! For life's ""sweet"" moments!",Food,Food,USD,2012-12-25,1500.0,2012-11-20 01:41:51,100.00,failed,3,US,100.00,100.00,1500.00
846,100413062,Corey’s Coffee Bar,Food,Food,USD,2013-02-22,6000.0,2013-01-23 20:31:25,10.00,failed,1,US,10.00,10.00,6000.00
936,1004687584,Bringing Patrizi's Back: A family food truck e...,Food,Food,USD,2013-03-02,30000.0,2013-01-25 18:06:17,40062.00,successful,117,US,40062.00,40062.00,30000.00
1030,100520530,Finish El Toro The Tot Food Trailer!!,Food,Food,USD,2013-04-28,28000.0,2013-03-29 06:37:11,28036.00,successful,75,US,28036.00,28036.00,28000.00
1056,1005286348,WANTED: THE BEST TASTING FUDGE ON EARTH (Cance...,Food,Food,AUD,2014-12-16,800.0,2014-10-17 00:17:35,0.00,canceled,0,AU,0.00,0.00,654.34
1086,1005457160,Spread the Love,Food,Food,USD,2014-10-08,7000.0,2014-09-08 22:53:59,0.00,failed,0,US,0.00,0.00,7000.00
1112,1005616872,The Dousing Sauce Story,Food,Food,USD,2015-06-01,25000.0,2015-04-08 07:55:56,100.00,failed,3,US,100.00,100.00,25000.00
1145,1005820753,tipstir,Food,Food,USD,2011-08-14,1000.0,2011-07-15 19:32:29,0.00,failed,0,US,0.00,0.00,1000.00
1182,1005987818,Sticky Boo Yum Yum | All Things Marshmallow,Food,Food,USD,2013-10-29,2350.0,2013-09-29 17:18:57,570.00,failed,38,US,570.00,570.00,2350.00
1330,1006835138,"Oh, Fudge!",Food,Food,USD,2011-11-16,5000.0,2011-09-17 03:51:54,1440.55,failed,63,US,1440.55,1440.55,5000.00
1355,1006945199,Have your Cake and Eat it too!,Food,Food,USD,2016-12-05,10000.0,2016-11-05 20:16:29,0.00,canceled,0,US,24.00,0.00,10000.00
1485,1007622469,Nourish Roshambo,Food,Food,USD,2013-06-15,4500.0,2013-05-16 09:12:40,600.00,failed,12,US,600.00,600.00,4500.00
1516,1007753223,Blue Haus Grill,Food,Food,USD,2014-04-10,3000.0,2014-03-11 20:07:47,100.00,failed,1,US,100.00,100.00,3000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377661,995047738,Put the SOLAR on Solar Crepes!,Food,Food,USD,2010-08-20,4754.8,2010-07-20 19:38:58,4755.00,successful,17,US,4755.00,4755.00,4754.80
377665,995075358,The Nutty Peanut,Food,Food,USD,2015-06-13,20000.0,2015-05-14 17:36:22,1220.00,failed,16,US,1220.00,1220.00,20000.00
377680,995155143,Car Guy Hot Sauce from The Busted Knuckle Garage,Food,Food,USD,2013-02-07,2000.0,2013-01-08 22:37:56,2071.00,successful,53,US,2071.00,2071.00,2000.00
377684,995170355,Bell and Whistle's Mobile Kitchen,Food,Food,USD,2011-04-03,6500.0,2011-03-02 05:18:35,6886.00,successful,106,US,6886.00,6886.00,6500.00
377757,995538414,Make a Tomato Pie !,Food,Food,USD,2014-09-14,10.0,2014-07-16 19:16:03,27.00,successful,8,US,27.00,27.00,10.00
377839,995949952,"Enchantments, an Artisans Bakery and Mystic Cr...",Food,Food,USD,2017-04-26,4750.0,2017-03-27 00:10:25,35.00,failed,2,US,92.00,35.00,4750.00
377853,996013662,Spice Box Co. Monthly Subscription Service,Food,Food,USD,2015-01-17,1000.0,2014-12-18 17:33:59,1055.00,successful,17,US,1055.00,1055.00,1000.00
377892,996256669,Messy Sex With Sexy Food,Food,Food,CAD,2016-10-15,1000.0,2016-09-16 17:44:32,172.00,failed,9,CA,103.02,130.02,755.92
377938,996519179,Simply Popped: Healthy Popcorn that is Simply...,Food,Food,USD,2015-06-08,9000.0,2015-05-04 18:35:18,48.00,failed,2,US,48.00,48.00,9000.00
377962,996636054,ICE ICE SHAVIE,Food,Food,USD,2012-05-27,15500.0,2012-04-12 00:53:48,295.00,failed,7,US,295.00,295.00,15500.00
377965,996648923,Eating Healthy Restaurant Review,Food,Food,USD,2014-08-07,100.0,2014-07-08 18:38:09,0.00,failed,0,US,0.00,0.00,100.00
378092,997330169,"GraceFull Community Cafe, Bringing People Toge...",Food,Food,USD,2015-10-24,10000.0,2015-09-24 03:11:19,11367.00,successful,91,US,11367.00,11367.00,10000.00
378110,997414993,TREEHOUSE TRUCK THE BREAKFAST EDITION (Canceled),Food,Food,USD,2011-09-02,10000.0,2011-07-19 00:14:42,171.50,canceled,8,US,171.50,171.50,10000.00
378119,997459366,An original family recipe for salsa,Food,Food,USD,2014-12-20,1500.0,2014-11-20 21:01:29,0.00,failed,0,US,0.00,0.00,1500.00
378125,997480149,Mo's Creations,Food,Food,GBP,2015-09-20,500.0,2015-08-21 09:59:29,20.00,failed,1,GB,31.36,30.35,758.83
378130,997495708,Novel Sweets,Food,Food,USD,2013-05-30,10000.0,2013-05-09 18:35:41,827.00,failed,18,US,827.00,827.00,10000.00
378135,997530846,Extra Virgin Coconut Oil - Supporting Our Comm...,Food,Food,GBP,2016-06-07,15000.0,2016-04-28 19:39:43,243.00,canceled,9,GB,354.34,350.01,21605.43
378150,997578229,Los Potosino's Gluten Free Flour Tortillas,Food,Food,USD,2012-04-03,10000.0,2012-02-18 08:33:25,753.00,failed,18,US,753.00,753.00,10000.00
378240,998020989,Lady D's Naked Treats,Food,Food,USD,2012-01-20,25000.0,2011-12-30 04:56:12,13700.00,failed,21,US,13700.00,13700.00,25000.00
378294,998281488,Southern Dry Rub,Food,Food,USD,2016-03-20,8000.0,2016-02-19 21:29:53,1.00,failed,1,US,1.00,1.00,8000.00
378350,998518353,Jem's Confections: Cupcakes and Cheesecake,Food,Food,USD,2016-10-26,8000.0,2016-10-05 04:16:52,2280.00,failed,29,US,1495.00,2280.00,8000.00
378351,998521148,Flawingos,Food,Food,USD,2015-08-30,100000.0,2015-07-31 16:23:02,0.00,failed,0,US,0.00,0.00,100000.00
378440,998909982,Frostbite Snowcones (Canceled),Food,Food,USD,2014-04-20,15000.0,2014-03-22 02:34:06,0.00,canceled,0,US,0.00,0.00,15000.00
378488,999120362,It's Time For Tea,Food,Food,USD,2010-06-30,3800.0,2010-05-16 22:54:44,500.00,failed,20,US,500.00,500.00,3800.00
378505,999198092,nanana (Suspended),Food,Food,USD,2015-08-07,1200.0,2015-07-08 22:41:49,13.00,suspended,1,US,13.00,13.00,1200.00
378509,999219271,"FaithWorks/Food Factory, Sauce, and Seasoning ...",Food,Food,USD,2015-08-15,15000.0,2015-07-22 17:44:54,600.00,failed,2,US,600.00,600.00,15000.00
378535,999331275,Please Help Me Create a Healthy cooking Club a...,Food,Food,USD,2015-03-11,150.0,2015-02-25 20:41:21,235.00,successful,10,US,235.00,235.00,150.00
378539,999354083,Project: Boyfriend Material,Food,Food,USD,2015-03-17,15.0,2015-02-25 07:22:48,66.00,successful,4,US,66.00,66.00,15.00
378545,99939527,"Snowdonia Gastropub - Coming soon to Astoria, NY!",Food,Food,USD,2013-04-22,9500.0,2013-04-06 01:59:13,11260.00,successful,37,US,11260.00,11260.00,9500.00
378573,999540977,Pin-Up Pastries wants to be your cupcake shop ...,Food,Food,USD,2011-08-06,5000.0,2011-07-07 06:18:58,125.00,failed,2,US,125.00,125.00,5000.00

3. .agg() - agregacja danych

In [0]:
df1.groupby('main_category').agg(min)

,ID,name,category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
main_category,,,,,,,,,,,,,,
Art,21109,"A Book, ""THE LIVING LINE: A 40 Year Odyssey T...",Art,AUD,2009-05-03,0.01,1970-01-01 01:00:00,0.0,canceled,0,AT,0.0,0.0,0.01
Comics,5971,! Bring Odessa a Comic Book/ Book Shop!,Anthologies,AUD,2009-06-15,1.00,2009-05-13 16:54:34,0.0,canceled,0,AT,0.0,0.0,0.72
Crafts,116600,"""A Happy Healthy Living with Soap!""",Candles,AUD,2009-06-16,1.00,2009-05-10 09:02:15,0.0,canceled,0,AT,0.0,0.0,1.00
Dance,285583,"""IdEgo"" 20th anniversary season",Dance,AUD,2009-11-06,5.00,2009-09-14 03:27:52,0.0,canceled,0,AT,0.0,0.0,5.00
Design,277920,! Online Library !,Architecture,AUD,2009-06-09,1.00,1970-01-01 01:00:00,0.0,canceled,0,AT,0.0,0.0,0.75
Fashion,33867,Expanding My Handmade Jewelry Collection!,Accessories,AUD,2009-05-26,1.00,2009-04-21 21:02:48,0.0,canceled,0,AT,0.0,0.0,0.77
Film & Video,39409,"""Pastriology"": a global documentary",Action,AUD,2009-05-20,0.15,1970-01-01 01:00:00,0.0,canceled,0,AT,0.0,0.0,0.15
Food,24380,We promise once you have bit of Poundtastic,Bacon,AUD,2009-05-31,1.00,2009-05-04 22:49:04,0.0,canceled,0,AT,0.0,0.0,0.88
Games,62304,!epacsE,Games,AUD,2009-06-15,1.00,2009-04-29 13:52:03,0.0,canceled,0,AT,0.0,0.0,0.75
Journalism,1228952,"Lucky Shot, a novel about sex, death and phot...",Audio,AUD,2009-05-16,1.00,2009-04-28 13:55:41,0.0,canceled,0,AT,0.0,0.0,1.00
Music,18520,"""Done With Error's,"" new EdGeR album and Film...",Blues,AUD,2009-05-16,1.00,1970-01-01 01:00:00,0.0,canceled,0,AT,0.0,0.0,0.74
Photography,336169,A New Sudan Through War or Peace,Animals,AUD,2009-06-02,1.00,2009-04-29 06:43:44,0.0,canceled,0,AT,0.0,0.0,1.00
Publishing,189772,IT’S A HOT CAPPUCCINO NIGHT,Academic,AUD,2009-05-29,0.01,1970-01-01 01:00:00,0.0,canceled,0,AT,0.0,0.0,0.01
Technology,21371,! SMART WINDOW SOLAR SYSTEM: Just Plug&Play,3D Printing,AUD,2009-06-01,1.00,2009-04-25 17:36:21,0.0,canceled,0,AT,0.0,0.0,0.73
Theater,342881,"""A TERRIBLE LIE,"" a new play by Jim Reyland",Comedy,AUD,2009-06-01,1.00,1970-01-01 01:00:00,0.0,canceled,0,AT,0.0,0.0,1.00

In [0]:
import pandas as pd
df = pd.DataFrame.from_records([( "A", 1,31),( "A", 2,41),( "A", 1,44), ( "A", 3,51), ("B",1,515), ("B",2,51),( "C", 2,155),( "C", 134)], columns = ["user", "prod_in_basket","basket_value"])


#groupby tworzy grupowanie po kolumnach, można podać listę kolumn jeżeli chcemy grupować po kilku kolumnach
df_groups = df.groupby(by = "user")
#w obrębie grup możemy policzyć różne statystyki po kolumnach które nie służycły do grupowania (w naszym przypadku "user")
#mamy dostępne funkcje typu sum, min, max... funkcja sum (itp) zwracają series, stąd trzeba je przekonwertować z powrotem do ramki danych (to_frame)
#kolumna z agregatami ma domyślnie nazwę kolumny na podstawie której ją policzono, można zmienić nazwę funkcją .rename
basket_size = df_groups['prod_in_basket'].sum().to_frame().rename(columns = {'prod_in_basket':'prod_in_basket_sum'})
print("*"*20,"\nbasket_size\n", basket_size)
basket_value = df_groups['basket_value'].sum().to_frame().rename(columns = {'basket_value':'basket_value_sum'})
print("*"*20,"\nbasket_value\n", basket_value)
basket_value_max = df_groups['basket_value'].max().to_frame().rename(columns = {'basket_value':'basket_value_max'})
print("*"*20,"\nbasket_value_max\n", basket_value_max)

#agregaty można połączyć w jedną ramkę funkcją cocnat, należy pamiętać o axis = 1, w przeciwnym razie każdy z agregatów zostanie potraktowany jako oddzielny wiersz
print(pd.concat([basket_size,basket_value,basket_value_max], axis = 1))
#w przykładzie wyżej kolumna grupująca traktowana jest jak indeks (nie jest to zwykła kolumna), żeby przywrócić user do zwykłych kolumn należy wykonać reset_index
print(pd.concat([basket_size,basket_value,basket_value_max], axis = 1).reset_index())

********************
basket_size
       prod_in_basket_sum
user
A                      7
B                      3
C                    136
********************
basket_value
       basket_value_sum
user
A                167.0
B                566.0
C                155.0
********************
basket_value_max
       basket_value_max
user
A                 51.0
B                515.0
C                155.0
      prod_in_basket_sum  basket_value_sum  basket_value_max
user
A                      7             167.0              51.0
B                      3             566.0             515.0
C                    136             155.0             155.0
  user  prod_in_basket_sum  basket_value_sum  basket_value_max
0    A                   7             167.0              51.0
1    B                   3             566.0             515.0
2    C                 136             155.0             155.0